## CSCE 676 :: Data Mining and Analysis :: Texas A&M University :: Fall 2025


# Homework 1: Let's GOOOOO!

- **100 points [7.5% of your final grade]**
- **Due Tuesday, September 14 by 11:59pm**

***Goals of this homework:***
1. Collect data from the web, clean it, and then make some observations based on exploratory data analysis
2. Understand and implement the classic apriori algorithm and extensions to find the association rules in a movie rating dataset
3. Push yourself by using Spark to find association rules

***Submission instructions:***

You should post your notebook to Canvas (look for the homework 1 assignment there). Please name your submission **your-uin_hw1.ipynb**, so for example, my submission would be something like **555001234_hw1.ipynb**. Your notebook should be fully executed when you submit ... so run all the cells for us so we can see the output, then submit that.

***Late Days:***

As a reminder, you begin the semester with five late days. You may use as many as you like. There is no need to alert us to how many late days you are using. Just submit and we will make note of it. Also remember that once your late days are used up, homeworks will receive a 0.

***Collaboration and AI Assistance declaration:***

If you worked with someone on this homework, please be sure to mention that. Remember to include citations to any sources you use in the homework. Also tell us what AI assistant you used and how you used it.

## (REQUIRED) Collaboration and AI Assistance Declaration

### Collaboration Declaration:

*your response goes here*

### AI Assistance Declaration:
gpt4.1 vscode chat for helper functions or quick syntax on longer operations\
haversine for lat/long->mi\
gpt5 did a lot of the spark step, I was having issues trying to run locally and eventually had to switch to colab\
general bug fixing


## (45 points) Part 1: UFO Sightings — Data Ingestion, Cleaning, and Feature Engineering

**Dataset:** `ufos.csv`

Detected columns: `datetime`, `city`, `state`, `country`, `shape`, `duration (seconds)`, `duration (hours/min)`, `comments`, `date posted`, `latitude`, `longitude`, and possibly extra unnamed columns.

**Goal:** Load the data, diagnose issues, clean/standardize it, and derive basic features to support downstream mining. You will probably want to use `pandas` for this.


### (5pts) Part 1a: Load and sanity-check the raw data

Tasks:
1. Load `ufos.csv` into a DataFrame named `ufo_raw`.
2. Display 5 random rows and `ufo_raw.info()`.
3. Briefly report the number of rows/columns and any obviously empty columns.

In [ ]:
import pandas as pd
pd.set_option('display.max_rows', None)

# Read columns as string first
ufo_raw = pd.read_csv(
    'ufos.csv',
    dtype=str,
    parse_dates=['datetime', 'date posted'],
    on_bad_lines='skip'
)

# Display 5 random rows and info
from random import randint
display(ufo_raw.sample(5, random_state=randint(0, 10000)))
ufo_raw.info()

def display_info(df):
    df.info()
    display(df.describe(include='all'))

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
27837,1/7/2013 01:50,anchorage,ak,us,NaN,0,still on,There are a 5-7 lights higher than a passenger...,1359936000000000000,61.2180556,-149.9002778
49143,5/26/2000 23:15,ogdensburg (over the st lawrence river on the ...,ny,NaN,changing,300,5 min,Circle of slowly strobbing white lights seen o...,960249600000000000,40.712784,-74.005941
43059,4/24/2010 21:50,london (uk/england),NaN,gb,flash,5,3-5 seconds,At approx 9.50 p.m. almost directly overhead&#...,1273622400000000000,51.514125,-.093689
62462,7/14/2007 23:00,springfield,tn,us,circle,120,2 minutes,circle object that flew in arch then disappeared,1186444800000000000,36.5091667,-86.8850000
63838,7/17/2003 15:15,portland,or,us,sphere,4500,1hr 15 min,Clearly visible&#44 stationary sphere&#44 &quo...,1058918400000000000,45.5236111,-122.6750000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88679 entries, 0 to 88678
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   datetime              88679 non-null  object
 1   city                  88679 non-null  object
 2   state                 81270 non-null  object
 3   country               76314 non-null  object
 4   shape                 85757 non-null  object
 5   duration (seconds)    88677 non-null  object
 6   duration (hours/min)  85660 non-null  object
 7   comments              88644 non-null  object
 8   date posted           88679 non-null  object
 9   latitude              88679 non-null  object
 10  longitude             88679 non-null  object
dtypes: object(11)
memory usage: 7.4+ MB

`datetime:`, `city:str`, `state`, `country`, `shape`, `duration (seconds)`, `duration (hours/min)`, `comments`, `date posted`, `latitude`, `longitude`


### (5pts) Part 1b: Clean up datatypes & columns

Create a cleaned DataFrame `ufo`:

- Drop fully-empty or irrelevant columns (e.g., unnamed columns).
- Parse `datetime` to `datetime64[ns]` (`errors='coerce'`).
- Coerce `duration (seconds)`, `latitude`, `longitude` to numeric.
- Lowercase/trim `city`, `state`, `country`, `shape`.
- Remove rows with impossible coordinates (lat ∉ [-90,90], lon ∉ [-180,180]).
- Drop exact duplicates based on a reasonable subset (document your choice).

Provide a short markdown note explaining your choices.

In [ ]:
import re
from datetime import datetime, timedelta

# datetime values with 24:00 get dropped when using pd.to_datetime
def fix_24_hour(dt_str):
    # Match date and time with 24:00
    match = re.match(r'(\d{1,2}/\d{1,2}/\d{2,4}) 24:00', str(dt_str))
    if match:
        # Parse date, add one day, set time to 00:00
        date_part = match.group(1)
        try:
            date_obj = datetime.strptime(date_part, '%m/%d/%Y')
        except ValueError:
            date_obj = datetime.strptime(date_part, '%m/%d/%y')
        new_dt = date_obj + timedelta(days=1)
        return new_dt.strftime('%m/%d/%Y 00:00')
    return dt_str

ufo = pd.DataFrame(ufo_raw)
# make 24:00 datetimes readable to pandas
ufo['datetime'] = ufo['datetime'].apply(fix_24_hour)
ufo['datetime'] = pd.to_datetime(ufo['datetime'], errors='coerce')

# Convert numeric columns, coercing errors to NaN
for col in ['duration (seconds)', 'latitude', 'longitude']:
    ufo[col] = pd.to_numeric(ufo[col], errors='coerce')
ufo = ufo[
    (ufo['latitude'] >= -90) & (ufo['latitude'] <= 90) &
    (ufo['longitude'] >= -180) & (ufo['longitude'] <= 180)
]
# Replace latitude and longitude values of 0 with NaN
ufo.loc[ufo['latitude'] == 0, 'latitude'] = None
ufo.loc[ufo['longitude'] == 0, 'longitude'] = None


# Convert other columns to desired types if needed
for col in ['city', 'state', 'country', 'shape', 'duration (hours/min)', 'comments']:
    ufo[col] = ufo[col].astype(str)
# Replace 'yk' with 'yt' in the 'state' column for the more commonly abv yukon territory
ufo['state'] = ufo['state'].replace('yk', 'yt')
# Set 'state' to 'vi' and 'pr' and 'us' for virgin islands and puerto rico
for x, y in [('virgin islands', 'vi'), ('puerto rico', 'pr')]:
    ufo.loc[
        (ufo['city'].str.lower().str.contains(x)) &
        ((ufo['state'].str.strip() == '') | (ufo['state'].str.lower() == 'nan')),
        'state'
    ] = y
    ufo.loc[
        (ufo['city'].str.lower().str.contains(x)) &
        ((ufo['country'].str.strip() == '') | (ufo['country'].str.lower() == 'nan')),
        'country'
    ] = 'us'
# for the more common country codes left blank
for x, y in [('canada', 'ca'), ('new zealand', 'nz'), ('south africa', 'za'), ('singapore', 'sg'), ('ireland', 'ie'), ('(italy)', 'it'), ('(mexico)', 'mx'), ('(uk/england)', 'gb'), ('(russia)', 'ru'), ('(lithuania)', 'lt'), ('(romania)', 'ro'), ('(india)', 'in'), ('iran', 'ir'), ('(iraq)', 'iq'), ('malaysia', 'myq'), ('australia', 'au'),('china', 'cn'), ('spain', 'es'), ('poland', 'pl'), ('greece', 'gr'), ('brazil', 'br'), ('portugal', 'pt'), ('south korea', 'kr'), ('japan', 'jp'), ('philippines', 'ph')]:
    ufo.loc[ # regex false because I want to include some parenthesis in city field
        (ufo['city'].str.lower().str.contains(x, regex=False)) &
        ((ufo['country'].str.strip() == '') | (ufo['country'].str.lower() == 'nan')),
        'country'
    ] = y
# List of two-letter US state abbreviations
us_states = [
    'al', 'ak', 'az', 'ar', 'ca', 'co', 'ct', 'de', 'fl', 'ga', 'hi', 'id', 'il', 'in', 'ia', 'ks', 'ky', 'la', 'me',
    'md', 'ma', 'mi', 'mn', 'ms', 'mo', 'mt', 'ne', 'nv', 'nh', 'nj', 'nm', 'ny', 'nc', 'nd', 'oh', 'ok', 'or', 'pa',
    'ri', 'sc', 'sd', 'tn', 'tx', 'ut', 'vt', 'va', 'wa', 'wv', 'wi', 'wy', 'dc'
]
# Set country to 'us' if state is a US abbreviation and country is missing or NaN
ufo.loc[
    (ufo['state'].str.lower().isin(us_states)) & (ufo['country'] == 'nan'),
    'country'
] = 'us'

ufo.info()
# duplicates = ufo[ufo.duplicated(keep=False)]
# print(duplicates)
# > no duplicates found

<class 'pandas.core.frame.DataFrame'>
Index: 88678 entries, 0 to 88678
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   datetime              88678 non-null  datetime64[ns]
 1   city                  88678 non-null  object
 2   state                 88678 non-null  object
 3   country               88678 non-null  object
 4   shape                 88678 non-null  object
 5   duration (seconds)    88676 non-null  float64
 6   duration (hours/min)  88678 non-null  object
 7   comments              88678 non-null  object
 8   date posted           88678 non-null  object
 9   latitude              87184 non-null  float64
 10  longitude             87184 non-null  float64
dtypes: datetime64[ns](1), float64(3), object(7)
memory usage: 8.1+ MB

### (5pts) Part 1c: Be thankful!

Now take a look at the `duration (hours/min)` column. In a previous version of this homework, students spent upwards of 10-20 hours just cleaning the values in this column. Luckily for you, the rest of this assignment relies on the much nicer `duration (seconds)` column. For this question, we'd like you to just extract how ever many versions of durations reported in *minutes* you can from the `duration (hours/min)` column. In other words, find as many different variations of anything that could be reasonably interpreted as a minute-like duration. Examples include:

* several minutes
* x to y minutes
* x minutes
* x min.
* x mins.
* and so on ...

In [ ]:
print(ufo['duration (hours/min)'].value_counts())
print(f'{len(ufo['duration (hours/min)'].value_counts())} different variations (including nan)')

duration (hours/min)
5 minutes                             4796
2 minutes                             3538
10 minutes                            3383
1 minute                              3118
nan                                   3019
3 minutes                             2553
30 seconds                            2350
15 minutes                            2105
10 seconds                            2016
5 seconds                             1836
20 minutes                            1467
1 hour                                1353
30 minutes                            1353
15 seconds                            1194
20 seconds                            1149
3 seconds                              945
4 minutes                              918
5 min                                  858
2 seconds                              699
10 min                                 662
2 hours                                661
2-3 minutes                            619
2 min                                  549
unknown                                528
45 seconds                             527
seconds                                525
1-2 minutes                            504
45 minutes                             500
1 min                                  495
15 min                                 478
4 seconds                              455
3 min                                  421
5 mins                                 371
5-10 minutes                           371
5 min.                                 352
20 min                                 347
1 second                               341
3-4 minutes                            337
3-5 minutes                            332
7 minutes                              330
60 seconds                             313
30 min                                 301
6 minutes                              298
8 minutes                              289
30 sec                                 287
3 hours                                277
10 mins                                274
6 seconds                              253
25 minutes                             245
10 sec                                 237
10 min.                                237
10-15 seconds                          234
2 min.                                 233
7 seconds                              210
10-15 minutes                          210
90 seconds                             210
2-3 seconds                            204
8 seconds                              204
40 seconds                             199
15 mins                                198
2 mins                                 196
5 sec                                  191
3 min.                                 185
15 min.                                184
40 minutes                             184
?                                      177
3 mins                                 175
15-20 minutes                          173
5-10 seconds                           172
one minute                             169
few seconds                            168
3-5 seconds                            166
25 seconds                             166
a few seconds                          166
15 sec                                 164
4 min                                  157
ongoing                                154
30 sec.                                149
15-20 seconds                          149
4-5 minutes                            148
30 mins                                147
30 min.                                145
45 min                                 144
5min                                   143
5-7 minutes                            142
20 mins                                142
20 sec                                 141
3-4 seconds                            140
20 min.                                136
4 hours                                135
12 minutes                             133
10 sec.                                131
2min                                   130
hours                                  128
20-30 seconds                          125
1min                                   125
5 sec.                                 124
several minutes                        124
10min                                  119
minutes                                114
few minutes                            114
1-2 seconds                            112
12 seconds                             110
1.5 minutes                            110
one hour                               109
15min                                  106
30-45 seconds                          103
15                                     100
five minutes                            98
10                                      96
35 minutes                              94
4-5 seconds                             91
1/2 hour                                90
a few minutes                           87
45 sec                                  86
not sure                                85
15 sec.                                 82
20 sec.                                 82
2 hrs                                   80
all night                               79
2-3 min                                 78
hour                                    78
1.5 hours                               75
2 sec                                   75
1 minutes                               75
1minute                                 74
35 seconds                              74
20-30 minutes                           72
3min                                    72
10 secs                                 70
30 secs                                 69
3 sec.                                  69
half hour                               69
3 sec                                   69
~1 minute                               69
30                                      69
2 sec.                                  69
1:00                                    68
30min                                   68
7 min                                   68
5minutes                                67
ten minutes                             66
1 sec                                   66
two minutes                             65
5-10 min                                65
5-6 minutes                             64
30seconds                               64
5-6 seconds                             63
~5 minutes                              63
45 min.                                 63
2-5 minutes                             63
5-7 seconds                             63
20min                                   62
4 min.                                  61
1-3 minutes                             60
<1 minute                               59
~2 minutes                              59
less than a minute                      59
5                                       58
5mins                                   58
1 hour +                                58
20                                      58
4 mins                                  58
10-15 min                               57
8-10 seconds                            57
4 sec                                   57
3-5 min                                 56
5-8 minutes                             55
90 minutes                              54
45 mins                                 54
50 seconds                              53
5 hours                                 53
1hr                                     52
2minutes                                52
45 sec.                                 52
1 to 2 minutes                          52
about 5 minutes                         51
25 min                                  50
1-2 min                                 50
30-40 seconds                           49
several hours                           49
2-4 minutes                             49
3 hrs                                   49
1:30                                    49
2mins                                   48
10-20 seconds                           48
about 2 minutes                         47
5 mins.                                 47
about 1 minute                          47
1                                       47
15-20 min                               46
30sec                                   46
8-10 minutes                            46
2-3 mins                                46
5 secs                                  45
50 minutes                              45
60 minutes                              44
~10 minutes                             44
15mins                                  44
1 min.                                  44
2:00                                    44
3 to 5 minutes                          43
2 to 3 minutes                          43
1.5 seconds                             43
40 min                                  42
15-30 seconds                           42
8 min                                   42
10sec                                   42
< 1 minute                              41
4 sec.                                  41
10minutes                               41
3-4 min                                 41
5-8 seconds                             41
30-60 seconds                           41
9 minutes                               41
1-2 min.                                41
2.5 hours                               40
on going                                40
1-2 hours                               40
60 sec                                  39
three minutes                           39
7-10 minutes                            38
night                                   38
minute                                  38
2-3 min.                                38
2                                       38
unsure                                  38
20 secs                                 37
3minutes                                37
5-10 mins                               37
15 secs                                 36
2-3 hours                               36
3-5 min.                                36
3-4 mins                                36
1 1/2 hours                             36
2hrs                                    36
6 hours                                 36
30+ minutes                             36
5-10 min.                               35
about 30 seconds                        35
10mins                                  35
still there                             35
3 to 4 minutes                          35
short                                   34
over an hour                            34
6 min                                   34
4min                                    34
30-45 minutes                           34
5 to 10 minutes                         34
5:00                                    33
1hour                                   33
3                                       33
about 10 minutes                        32
less than 1 minute                      32
2 hrs.                                  32
7-10 seconds                            32
5 - 10 minutes                          32
3-4 min.                                32
40 sec                                  32
15minutes                               32
45-60 seconds                           31
current                                 31
1 sec.                                  31
17 minutes                              31
2+ hours                                31
5 to 10 seconds                         31
5min.                                   30
2.5 minutes                             30
ten seconds                             30
5sec                                    30
10-12 minutes                           30
1-2 mins                                30
10-20 minutes                           29
photo                                   29
1 1/2 minutes                           29
1 hr                                    29
10seconds                               28
7 mins                                  28
split second                            28
several seconds                         28
5-7 min                                 28
brief                                   28
60-90 seconds                           28
45min                                   27
10-12 seconds                           27
continuous                              27
about 3 minutes                         27
6 sec                                   27
15seconds                               27
1.5 min                                 27
3:00                                    26
6 min.                                  26
2-4 seconds                             26
7 min.                                  26
3 secs                                  26
9 seconds                               26
don&#39t know                           25
two hours                               25
15-20 mins                              25
20-25 seconds                           25
ufo                                     25
10min.                                  25
13 minutes                              25
2 - 3 minutes                           25
20seconds                               25
>1 hour                                 25
12 min                                  25
15sec                                   25
60 sec.                                 25
about an hour                           24
30mins                                  24
5 mintues                               24
about a minute                          24
10-15 sec.                              24
3 mins.                                 24
1min.                                   24
still going                             24
90 sec                                  24
2 mins.                                 24
unk                                     24
8 sec                                   24
30minutes                               23
2 minute                                23
20 mins.                                23
16 minutes                              23
unkown                                  23
35 min                                  23
18 minutes                              23
3mins                                   23
20mins                                  23
3sec                                    23
5-10 sec                                23
120 seconds                             22
20minutes                               22
15 mins.                                22
10-15 sec                               22
6-8 seconds                             22
2 or 3 minutes                          22
2-3 sec                                 22
about 5 seconds                         22
1+ hour                                 22
6 mins                                  22
~3 minutes                              22
:30                                     22
one second                              22
8 min.                                  22
30-40 minutes                           22
10-15 min.                              22
6-7 minutes                             22
40 mins                                 21
10-15 mins                              21
still happening                         21
25 min.                                 21
11 minutes                              21
25 sec                                  21
90 sec.                                 21
1.5 hrs                                 21
15 to 20 seconds                        21
5+ minutes                              21
5seconds                                21
25-30 seconds                           20
second                                  20
30 mins.                                20
2 secs                                  20
10 to 15 seconds                        20
10 to 15 minutes                        20
4 to 5 minutes                          20
6 sec.                                  20
10:00                                   20
15-20 sec                               20
2min.                                   20
4-6 minutes                             20
8 mins                                  20
about 10 seconds                        20
2 to 3 seconds                          20
20-30 sec                               19
7-8 seconds                             19
30-45 sec                               19
20-30 min                               19
5 - 10 seconds                          19
4-5 min                                 19
3 to 4 seconds                          19
20-25 minutes                           19
15min.                                  19
6-7 seconds                             18
40 min.                                 18
continuing                              18
15-20 min.                              18
10 - 15 seconds                         18
~1 hour                                 18
15 to 20 minutes                        18
na                                      18
five seconds                            18
4minutes                                18
1-3 seconds                             18
3 days                                  18
15-30 minutes                           18
10+ minutes                             18
??                                      17
~30 seconds                             17
3-4 sec                                 17
4 to 5 seconds                          17
20sec                                   17
less than 1 min                         17
still going on                          17
3 to 5 seconds                          17
3 hrs.                                  17
10 - 15 minutes                         17
???                                     17
30secs                                  17
20+ minutes                             17
1 hour or more                          17
30sec.                                  17
05 minutes                              17
about 15 minutes                        17
half an hour                            17
7 sec                                   17
an hour                                 17
8 hours                                 16
approx 1 minute                         16
6-8 minutes                             16
15 - 20 minutes                         16
25 mins                                 16
15:00                                   16
2 hours +                               16
00:10                                   16
2hours                                  16
1 hour plus                             16
1/2 second                              16
5 minute                                16
less than 5 minutes                     16
15-20 sec.                              16
1 minute or so                          15
7 sec.                                  15
2-5 seconds                             15
30-45 sec.                              15
8 sec.                                  15
<2 minutes                              15
2sec                                    15
45                                      15
00:30                                   15
1 or 2 minutes                          15
22 minutes                              15
25min                                   15
5 minutes?                              15
3min.                                   15
3 - 5 minutes                           15
2 minutes?                              14
00:20                                   14
3 to 5 min                              14
5 to 7 minutes                          14
2-3minutes                              14
approx 2 minutes                        14
4 secs                                  14
<5 minutes                              14
less than 30 seconds                    14
4mins                                   14
25-30 minutes                           14
30min.                                  14
3-5min                                  14
uncertain                               14
14 minutes                              14
10-15min                                14
about 1 hour                            14

In [ ]:
# Replace any sequence of digits with 'x' in the 'duration (hours/min)' column and create a new Series
duration_x = ufo['duration (hours/min)'].str.replace(r'\d+', 'x', regex=True)
print(duration_x.value_counts())
print(f'{len(duration_x.value_counts())} different variations when we remove specific numbers')
# If I were to try to clean this column I would pull the first number, scan for 'm','h', then 's' and set the value to num,num*60,num/60 respectively
# this would lose accuracy for fractioned or interval entries, but would give us something close to work with

duration (hours/min)
x minutes                          22776
x seconds                          13190
x min                               4779
x-x minutes                         3695
x minute                            3199
nan                                 3019
x-x seconds                         2404
x min.                              1835
x mins                              1787
x sec                               1601
x hour                              1360
x hours                             1227
x sec.                               987
xmin                                 972
x:x                                  885
x                                    683
x-x min                              592
unknown                              528
seconds                              525
x second                             410
x secs                               385
x to x minutes                       362
xminutes                             350
x-x min.                             317
x-x mins                             312
xmins                                303
x to x seconds                       297
xsec                                 279
x-x sec                              269
~x minutes                           263
xseconds                             253
about x minutes                      224
x mins.                              206
xmin.                                183
?                                    177
x-x sec.                             176
x.x minutes                          170
one minute                           169
few seconds                          168
a few seconds                        166
x hrs                                166
x - x minutes                        159
ongoing                              154
about x seconds                      151
x+ minutes                           146
x - x seconds                        144
x.x hours                            140
hours                                128
several minutes                      124
x-xmin                               116
minutes                              114
x-x hours                            114
few minutes                          114
one hour                             109
x to x min                           109
five minutes                          98
x-x secs                              93
x/x hour                              92
a few minutes                         87
not sure                              85
x.x seconds                           79
all night                             79
hour                                  78
~x seconds                            77
xminute                               77
x:x:x                                 72
x or x minutes                        71
:x                                    70
x minutes?                            70
x-xminutes                            70
~x minute                             70
half hour                             69
x.x                                   69
xsec.                                 68
ten minutes                           66
x+ hours                              65
two minutes                           65
x-xmins                               65
x hrs.                                63
x minutes +                           61
approx. x minutes                     60
xhr                                   60
x to x mins                           59
<x minute                             59
x to x min.                           59
less than a minute                    59
x hour +                              58
x-x                                   58
x-xseconds                            58
about x min                           58
xhrs                                  58
x x/x hours                           57
x:x minutes                           56
x secs.                               55
x:x-x:x                               55
x to x sec                            55
x.x min                               54
x-x mins.                             53
x days                                52
approx. x min.                        52
<x seconds                            52
x minuts                              51
approx x min                          51
x mintues                             51
x seconds?                            50
xsecs                                 50
several hours                         49
x or x seconds                        49
about x minute                        48
approx x minutes                      47
x-xsec                                47
about x min.                          45
less than x seconds                   44
x  minutes                            42
>x minutes                            42
x x/x minutes                         42
< x minute                            41
<x minutes                            41
on going                              40
three minutes                         39
x hr                                  39
minute                                38
unsure                                38
night                                 38
x minutes+                            36
x - x min                             36
x minuets                             35
x to x sec.                           35
still there                           35
about x mins                          35
x:x min                               35
x -x minutes                          35
short                                 34
over an hour                          34
xhour                                 33
x -x seconds                          32
.x                                    32
xhours                                32
less than x minute                    32
current                               31
x/x second                            30
ten seconds                           30
photo                                 29
x min +                               29
less than x minutes                   29
x minutes or so                       29
several seconds                       28
brief                                 28
split second                          28
x.x hrs                               28
continuous                            27
x secounds                            27
approx: x minutes                     26
x/x minutes                           26
approx x seconds                      26
at least x minutes                    26
don&#xt know                          25
ufo                                   25
>x hour                               25
two hours                             25
about x-x minutes                     24
about a minute                        24
approx: x seconds                     24
x hours +                             24
still going                           24
unk                                   24
about an hour                         24
x+                                    24
unkown                                23
xs                                    23
x-x secs.                             23
approx. x seconds                     23
x.x sec                               23
x+ hour                               22
approximately x minutes               22
x-xmin.                               22
x minuites                            22
one second                            22
less than x min                       22
x min x sec                           21
still happening                       21
x minutes approx                      21
x - x min.                            20
x seconds or so                       20
second                                20
x seconds or less                     20
x  seconds                            19
x -x min                              19
approx. x min                         19
x to x hours                          19
na                                    18
x nights                              18
about x sec.                          18
~x-x minutes                          18
five seconds                          18
continuing                            18
x minutes or less                     18
x - x mins                            18
approx x sec                          18
x x/x hrs                             18
x minutes or more                     18
xm                                    18
~x hour                               18
an hour                               17
??                                    17
x minutes plus                        17
???                                   17
still going on                        17
approx x min.                         17
x hour or more                        17
x:xmin                                17
x:x min.                              17
x mins +                              17
x:xpm                                 17
x+ seconds                            17
half an hour                          17
x.min                                 17
x min approx                          17
about x hours                         17
over x minutes                        17
x.x mins                              16
approx x minute                       16
.x seconds                            16
x-x hrs                               16
x-x minute                            16
x hour plus                           16
x.x min.                              16
x hour x minutes                      16
x weeks                               16
approx. x sec.                        16
x min+                                16
x minute or so                        15
x&#x                                  15
x min. approx.                        15
over x hours                          15
xmins.                                15
x minites                             15
x-xsec.                               15
x/x seconds                           15
x to x mins.                          15
x min?                                15
~x min                                15
about x sec                           14
uncertain                             14
x minutes approx.                     14
about x hour                          14
x  min                                14
x or x min.                           14
x minutes ?                           14
aprox x min                           14
>x min                                14
xmin+                                 14
approx. x mins                        14
none                                  13
x minutos                             13
x-xsecs                               13
x.x hrs.                              13
x min. +                              13
couple minutes                        13
x:x - x:x                             13
x+minutes                             13
< x min                               13
less than x min.                      13
not known                             13
twenty minutes                        13
x/x/x                                 13
x hr x min                            13
less than one minute                  13
momentary                             13
xhr xmin                              13
x + minutes                           13
xmin xsec                             13
xmin x sec                            12
instant                               12
x:x to x:x                            12
x - x sec                             12
x minutes (approx.)                   12
x - x sec.                            12
varies                                12
x-x  seconds                          12
aprox x minutes                       12
at least x hour                       12
around x seconds                      12
x x/x min.                            12
three seconds                         11
x.x hour                              11
around x minutes                      11
less than x second                    11
x s                                   11
approx x mins                         11
x min&#xs                             11
x+ min                                11
west                                  11
< x seconds                           11
<x second                             11
~ x minutes                           11
x- x minutes                          11
x-minutes                             11
x min or less                         11
x-x  minutes                          11
about one minute                      11
x:x mins                              11
x.xmin                                11
picture                               11
x.xhrs                                11
x mn                                  10
>x hours                              10
x-xhrs                                10
over x hour                           10
flash                                 10
x minute or less                      10
x hours?                              10
morning                               10
x + hours                             10
home                                  10
constant                              10
dont know                             10
x- x seconds                          10
x:x minute                            10
three hours                           10
unknow                                 9
north                                  9
x hours+                               9
x week                                 9
approx x hour                          9
x hour+                                9
a minute or so                         9
still ongoing                          9
x minute x seconds                     9
at least an hour                       9
less then a minute                     9
x m                                    9
x-x days                               9
x minutess                             9
x mins?                                9
x minute +                             9
two seconds                            9
x minutes.                             9
couple seconds                         9
about x mins.                          9
x miutes                               9
moments                                9
x min or so                            9
approx. x minute                       9
still                                  9
driving                                9
a few hours                            9
less than x sec                        9
long time                              9
x seconds to x minute                  9
~x mins                                8
x-min                                  8
approximately x seconds                8
x-x mintues                            8
x months                               8
aprox. x minutes                       8
x min. x sec.                          8
lights                                 8
nightly                                8
approx. x hour                         8
still occuring                         8
x-x minuets                            8
x minues                               8
about xmin                             8
x minute?                              8
x to x secs                            8
months                                 8
.x sec                                 8
four minutes                           8
x/x minute                             8
x-x second                             8
x minutes x seconds                    8
x-min.                                 8
x plus minutes                         8
x min. ?                               8
xsecond                                8
x or x mins                            8
x:x seconds                            8
on-going                               8
very short                             8
now                                    8
a minute                               8
under x minute                         8
east                                   8
less than a second                     8
less then x seconds                    8
days                                   8
x minutes +/-                          8
snapshot                               8
x - x secs                             8
x mins approx                          8
x.x sec.                               8
very brief                             8
x- x min                               8
approx.x min.                          8
x hours plus                           8
x miniutes                             8
fifteen minutes                        8
long                                   8
x+ min.                                8
x x/x hour                             8
hour and half                          8
x.x-x minutes                          8
x-x.x minutes                          8
>x seconds                             8
< x minutes                            8
about x-x seconds                      8
x:x pm                                 7
@ x minutes                            7
x x/x hrs.                             7
~x hours                               7
x mimutes                              7
xmn                                    7
x or x min                             7
ufo sighting                           7
approximately x minute                 7
approx. x mins.                        7
x-xhours                               7
xhrs.                                  7
????                                   7
x-xmins.                               7
one min                                7
at least x min                         7
a minute or two                        7
< x second                             7
:x seconds                             7
roughly x minutes                      7
x minutes each                         7
one min.                               7
x seconds ?                            7
seven minutes                          7
x sec&#xs                              7
x hour?                                7
x secconds                             7
i don&#xt know                         7
at least x hours                       7
few hours                              7
x-seconds                              7
~x second                              7
x min.?                                7
under x seconds                        7
x hour x min                           7
x+ mins                                7
x -x mins                              7
approx: x sec.                         7
about x secs                           7
x minits                               7
all day                                7
hour and a half                        7
approx xmin                            6
around x min                           6
x minutes (?)                          6
x hr.                                  6
x - x hours                            6
x.x second                             6
x minets                               6
few mins                               6
six minutes                            6
.x second                              6
< x sec                                6
x/x min                                6
x/x hr.                                6
less than minute                       6
x seconds.                             6
x  min.                                6
x+min                                  6
x/x sec                                6
xtoxmin                                6
x minutes total                        6
x min x seconds                        6
thirty minutes                         6
sighting                               6
x+ mins.                               6
x minute or more                       6
>x minute                              6
x.xsec                                 6
couple of seconds                      6
a couple of seconds                    6
xhrxmin                                6
xhr +                                  6
x/x mins                               6
sky                                    6
x min ?                                6
x secondes                             6
x+hours                                6
fast                                   6
x min.s                                6

In [ ]:
# Only pull values from 'duration (hours/min)' that contain 'm', then replace digits with 'x'
duration_x_m = ufo.loc[ufo['duration (hours/min)'].str.contains('m', case=False, na=False), 'duration (hours/min)'].str.replace(r'\d+', 'x', regex=True)
print(duration_x_m.value_counts())
print(f'{len(duration_x_m.value_counts())} different variations when we only include values believed to be in minutes')
# this approach is simple, assuming any value with 'm' is in minutes
# this will neglect values without units such as x:x (containing multiple units)

duration (hours/min)
x minutes                          22776
x min                               4779
x-x minutes                         3695
x minute                            3199
x min.                              1835
x mins                              1787
xmin                                 972
x-x min                              592
x to x minutes                       362
xminutes                             350
x-x min.                             317
x-x mins                             312
xmins                                303
~x minutes                           263
about x minutes                      224
x mins.                              206
xmin.                                183
x.x minutes                          170
one minute                           169
x - x minutes                        159
x+ minutes                           146
several minutes                      124
x-xmin                               116
few minutes                          114
minutes                              114
x to x min                           109
five minutes                          98
a few minutes                         87
xminute                               77
x or x minutes                        71
x-xminutes                            70
~x minute                             70
x minutes?                            70
ten minutes                           66
x-xmins                               65
two minutes                           65
x minutes +                           61
approx. x minutes                     60
<x minute                             59
less than a minute                    59
x to x mins                           59
x to x min.                           59
about x min                           58
x:x minutes                           56
x.x min                               54
x-x mins.                             53
approx. x min.                        52
x mintues                             51
x minuts                              51
approx x min                          51
about x minute                        48
approx x minutes                      47
about x min.                          45
>x minutes                            42
x  minutes                            42
x x/x minutes                         42
< x minute                            41
<x minutes                            41
three minutes                         39
minute                                38
x - x min                             36
x minutes+                            36
x minuets                             35
x -x minutes                          35
about x mins                          35
x:x min                               35
less than x minute                    32
x min +                               29
less than x minutes                   29
x minutes or so                       29
approx: x minutes                     26
x/x minutes                           26
at least x minutes                    26
about a minute                        24
about x-x minutes                     24
x minuites                            22
approximately x minutes               22
x-xmin.                               22
less than x min                       22
x min x sec                           21
x minutes approx                      21
x - x min.                            20
approx. x min                         19
x -x min                              19
x minutes or more                     18
x minutes or less                     18
~x-x minutes                          18
x - x mins                            18
xm                                    18
x.min                                 17
x mins +                              17
approx x min.                         17
x:xmin                                17
x minutes plus                        17
x:xpm                                 17
x hour or more                        17
x min approx                          17
over x minutes                        17
x:x min.                              17
x-x minute                            16
x hour x minutes                      16
x min+                                16
x.x min.                              16
approx x minute                       16
x.x mins                              16
x minute or so                        15
x to x mins.                          15
x min. approx.                        15
x min?                                15
x minites                             15
xmins.                                15
~x min                                15
x  min                                14
xmin+                                 14
approx. x mins                        14
>x min                                14
aprox x min                           14
x or x min.                           14
x minutes approx.                     14
x minutes ?                           14
momentary                             13
less than x min.                      13
x hr x min                            13
x + minutes                           13
xmin xsec                             13
x+minutes                             13
x min. +                              13
< x min                               13
less than one minute                  13
x minutos                             13
twenty minutes                        13
xhr xmin                              13
couple minutes                        13
x x/x min.                            12
x minutes (approx.)                   12
xmin x sec                            12
aprox x minutes                       12
x.xmin                                11
approx x mins                         11
about one minute                      11
around x minutes                      11
x min or less                         11
x min&#xs                             11
x- x minutes                          11
x:x mins                              11
~ x minutes                           11
x+ min                                11
x-minutes                             11
x-x  minutes                          11
morning                               10
x mn                                  10
home                                  10
x:x minute                            10
x minute or less                      10
x min or so                            9
x miutes                               9
x minute +                             9
x minutes.                             9
x seconds to x minute                  9
x minute x seconds                     9
x minutess                             9
about x mins.                          9
moments                                9
x m                                    9
a minute or so                         9
x mins?                                9
approx. x minute                       9
long time                              9
less then a minute                     9
x+ min.                                8
< x minutes                            8
fifteen minutes                        8
x min. ?                               8
x minues                               8
x-x minuets                            8
x-min                                  8
approx.x min.                          8
x months                               8
x minutes +/-                          8
x-x mintues                            8
x minute?                              8
aprox. x minutes                       8
x-x.x minutes                          8
~x mins                                8
x.x-x minutes                          8
x min. x sec.                          8
x plus minutes                         8
x mins approx                          8
x- x min                               8
x-min.                                 8
four minutes                           8
x minutes x seconds                    8
x or x mins                            8
x/x minute                             8
months                                 8
about xmin                             8
x miniutes                             8
approximately x seconds                8
a minute                               8
under x minute                         8
roughly x minutes                      7
x:x pm                                 7
x hour x min                           7
seven minutes                          7
x mimutes                              7
x or x min                             7
x min.?                                7
x-xmins.                               7
one min.                               7
approximately x minute                 7
approx. x mins.                        7
x -x mins                              7
x minutes each                         7
a minute or two                        7
one min                                7
@ x minutes                            7
x+ mins                                7
x minits                               7
xmn                                    7
at least x min                         7
xhrxmin                                6
>x minute                              6
x minute or more                       6
x minute approx.                       6
x mins+                                6
few mins                               6
x/x min                                6
x minutes at least                     6
approx xmin                            6
appx x min                             6
xhr x min                              6
xminutes+                              6
thirty minutes                         6
aprox. x min                           6
x sec - x min                          6
x+min                                  6
x.minutes                              6
x minutes total                        6
x minutes (?)                          6
xsec-xmin                              6
x min ?                                6
aprox. x min.                          6
x min.s                                6
x minets                               6
aprox xmin                             6
xtoxmin                                6
less than minute                       6
six minutes                            6
x/x mins                               6
x+min.                                 6
x minutes aprox                        6
x  min.                                6
x min x seconds                        6
around x min                           6
a couple of minutes                    6
x+ mins.                               6
approx. x-x min.                       5
x seconds - x minute                   5
x - x mins.                            5
approx x-x minutes                     5
pm                                     5
hour or more                           5
x.x to x minutes                       5
couple of minutes                      5
xo minutes                             5
app. x minutes                         5
~x min.                                5
several min.                           5
~x.x minutes                           5
x hours x minutes                      5
less than xmin                         5
x min xsec                             5
<x min                                 5
about three minutes                    5
<xmin                                  5
appx. x minutes                        5
x min approx.                          5
x min or more                          5
x hr x minutes                         5
<x min.                                5
x hours or more                        5
x min plus                             5
x min&#x                               5
x/xmin                                 5
x seconds to a minute                  5
x or more hours                        5
more than x minutes                    5
under a minute                         5
a couple minutes                       5
x x/x min                              5
aprox x minute                         5
x minute approx                        5
under x minutes                        5
x-minute                               5
approx x mins.                         5
xminxsec                               4
five mins                              4
x min. plus                            4
x.x minute                             4
app. x min.                            4
about a min                            4
x x/x - x minutes                      4
x min +/-                              4
x x minutes                            4
x min x secs                           4
xmin x seconds                         4
under x min                            4
xmin xsecs                             4
x-x minutes.                           4
x to x.x minutes                       4
around a minute                        4
x&#x min.                              4
around x minute                        4
x miuntes                              4
xmin.xsec.                             4
x-x minutess                           4
x min max                              4
over x min                             4
x mins or so                           4
x  mins                                4
x hr x mins                            4
more than x hour                       4
x seconds maybe                        4
xminute x seconds                      4
ten min                                4
around x mins                          4
xhr xmins                              4
appr. x min.                           4
x minuted                              4
x/x min.                               4
x-mins                                 4
x to xminutes                          4
x hrs. x min.                          4
x minutes (approx)                     4
~ x min                                4
night time                             4
x minute plus                          4
x- x mins                              4
x+ minute                              4
x times                                4
camping                                4
+/- x minutes                          4
.x minutes                             4
one minute or less                     4
x minutes approximately                4
< xmin                                 4
app x min                              4
approx xmins                           4
five min                               4
+x minutes                             4
x sec-xmin                             4
x seconds max                          4
x minuits                              4
x:x am                                 4
approx: x mins                         4
x min. approx                          4
x min total                            4
x tox min                              4
xmin. xsec.                            4
many hours                             4
x minutes or longer                    3
x xr x minutes                         3
nighttime                              3
xminute +                              3
x minnutes                             3
x mins aprox                           3
@ x min                                3
app. x min                             3
x-x minues                             3
several mins                           3
i minute                               3
about x-x min.                         3
x mns                                  3
x-x/x minutes                          3
x munites                              3
x minutes to an hour                   3
a few moments                          3
about xmin.                            3
x hours&#x x minutes                   3
x.xmins                                3
xmin-xhr                               3
x miinutes                             3
a minute or less                       3
one minute or so                       3
xhour x min                            3
about five minutes                     3
x/xmins                                3
moment                                 3
x minute&#xs                           3
xtox minutes                           3
< x min.                               3
x min.+                                3
approx. xmin                           3
x-x-mins                               3
one to two minutes                     3
xmin aprox                             3
x seconds approximately                3
x mn.                                  3
x mim                                  3
x minutes +-                           3
about ten minutes                      3
x hours and x minutes                  3
x min. (approx.)                       3
x-x min&#xs                            3
one or two minutes                     3
less than x mins                       3
xorxmin                                3
x minutew                              3
over x mins                            3
few min                                3
x hour and x minutes                   3
xto x minutes                          3
x min x sec.                           3
x minutea                              3
almost x hours                         3
at home                                3
two min                                3
x:xminutes                             3
x:xpm-x:xpm                            3
about xminutes                         3
x minutes max                          3
x hour x mins                          3
@x minutes                             3
x-x minutes?                           3
aprox x min.                           3
x minutes and counting                 3
x. min                                 3
x minute +/-                           3
less than a min                        3
maybe x min.                           3
around x min.                          3
x minitues                             3
x seconds to one minute                3
my house                               3
x+mins                                 3
most of the night                      3
xminets                                3
at least five minutes                  3
xhour x mins                           3
approx; x minutes                      3
matter of seconds                      3
xmin-xmin                              3
-x minutes                             3
apx x min                              3
x min aprox                            3
appx. x min.                           3
>xmins                                 3
xmin?                                  3
five to ten minutes                    3
xmn.                                   3
x min-x hour                           3
xtox min                               3
xmin approx                            3
x min. x secs.                         3
xmins+                                 3
@ x min.                               3
:x min                                 3
x minuet                               3
x&#xmin.                               3
x hr. x min.                           3
apx. x minutes                         3
half minute                            3
x min to x hr                          3
x-x miniutes                           3
a long time                            3
early morning                          3
at least x mins                        3
x to x minuets                         3
about x to x minutes                   3
x hr x min.                            3
x minustes                             3
x minutes on and off                   3
ten min.                               3
x mintutes                             3
x  to x minutes                        3
~ x minute                             3
maybe a minute                         3
xtox min.                              3
x min. ??                              3
x&#xminutes                            3
dream                                  3
x hour x min.                          3
x-x minutes each                       3
some minutes                           3
xmm                                    3
x.xminutes                             2
~x mins.                               2


### (10pts) Part 1d: Feature engineering and small exploratory data analysis

Create additional columns in a new feature engineering version of the dataset called `ufo_fe`:

- `year`, `month`, `hour` from `datetime`
- `duration_log10` = log10(duration_seconds + 1)
- `duration_bucket` = categorical bins for `duration (seconds)` (you may adjust edges)
- `us_only` = 1 if `country == 'us'` else 0

Then produce:
- Value counts of `shape` (top 10).
- A table of sightings by `year` (counts).
- A `state × shape` table (top 10 states by sample size).

In [ ]:
from math import log10
ufo_fe = pd.DataFrame(ufo)
ufo_fe['year'] = ufo_fe['datetime'].dt.year
ufo_fe['month'] = ufo_fe['datetime'].dt.month
ufo_fe['hour'] = ufo_fe['datetime'].dt.hour
ufo_fe['duration_log10'] = ufo_fe['duration (seconds)'].apply(lambda x: log10(x + 1))
# Create duration_bucket column with categorical bins for 'duration (seconds)'
bins = [0, 10, 60, 300, 1800, 3600, 21600, 86400, float('inf')]
labels = ['<10s', '10s-1m', '1m-5m', '5m-30m', '30m-1h', '1h-6h', '6h-24h', '>24h']
ufo_fe['duration_bucket'] = pd.cut(ufo_fe['duration (seconds)'], bins=bins, labels=labels, right=False)
ufo_fe['us_only'] = ufo_fe['country'].apply(lambda x: 1 if x == 'us' else 0)

print(f'Top 10 shapes:')
print(ufo_fe['shape'].value_counts()[:10])
year_counts = ufo_fe['year'].value_counts().sort_index().to_frame(name='count')
print(f'\nCount of Sightings by year:')
display(year_counts)
top_states = ufo_fe[~ufo_fe['state'].str.lower().isin(['nan', '', 'none'])]['state'].value_counts().head(10).index
top_states_df = ufo_fe[ufo_fe['state'].isin(top_states)][['state', 'shape']]
top_states_df = top_states_df.reset_index(drop=True)
print(f'description about the (large) state x shape table:')
top_states_df.describe()
print(top_states,'\n',top_states_df.columns)
print(top_states_df.value_counts())

Top 10 shapes:
shape
light       17872
triangle     8489
circle       8453
fireball     6562
unknown      6319
other        6247
disk         6005
sphere       5755
oval         4119
nan          2922
Name: count, dtype: int64

Count of Sightings by year:

      count
year
1906      1
1910      3
1914      1
1916      1
1917      1
1920      2
1925      1
1929      1
1930      2
1931      2
1933      1
1934      1
1935      1
1936      3
1937      2
1939      3
1941      3
1942      5
1943     10
1944     13
1945     14
1946     10
1947     45
1948     11
1949     19
1950     33
1951     25
1952     58
1953     39
1954     62
1955     40
1956     52
1957     84
1958     56
1959     61
1960     77
1961     54
1962     83
1963     94
1964    103
1965    207
1966    225
1967    220
1968    244
1969    178
1970    171
1971    139
1972    199
1973    253
1974    299
1975    356
1976    314
1977    300
1978    380
1979    279
1980    281
1981    195
1982    211
1983    181
1984    204
1985    241
1986    222
1987    249
1988    268
1989    284
1990    293
1991    261
1992    291
1993    359
1994    476
1995   1441
1996    986
1997   1403
1998   1993
1999   3123
2000   3054
2001   3482
2002   3636
2003   4389
2004   4700
2005   4465
2006   4111
2007   4673
2008   5225
2009   4933
2010   4690
2011   5521
2012   7924
2013   7599
2014   2473

description about the (large) state x shape table:
Index(['ca', 'wa', 'fl', 'tx', 'ny', 'az', 'il', 'pa', 'oh', 'mi'], dtype='object', name='state')
 Index(['state', 'shape'], dtype='object')
state  shape
ca     light        2105
wa     light         979
ca     circle        977
       triangle      939
fl     light         877
tx     light         807
ca     fireball      785
       disk          763
       other         731
       sphere        707
az     light         663
ca     unknown       663
ny     light         660
il     light         583
pa     light         545
oh     light         498
fl     fireball      481
ca     oval          454
mi     light         452
fl     circle        432
tx     triangle      410
fl     triangle      409
wa     nan           406
       fireball      397
       triangle      378
       circle        375
ny     circle        363
ca     nan           362
wa     unknown       356
il     triangle      348
tx     circle        345
ny     triangle      344
fl     unknown       339
ca     formation     337
tx     other         331
       unknown       328
ca     changing      322
fl     other         313
wa     other         310
fl     sphere        303
wa     sphere        300
il     circle        297
oh     triangle      288
tx     disk          277
fl     disk          275
az     triangle      273
ny     disk          269
pa     triangle      269
       circle        269
az     circle        265
oh     circle        259
mi     triangle      258
oh     fireball      248
ny     fireball      247
pa     fireball      242
ny     other         238
az     other         236
tx     sphere        233
ny     unknown       232
fl     oval          232
ca     cigar         230
wa     disk          229
tx     fireball      228
il     fireball      228
tx     oval          221
pa     unknown       216
ny     sphere        202
az     unknown       201
oh     sphere        200
wa     oval          199
mi     fireball      199
ny     oval          196
az     fireball      195
pa     other         189
il     unknown       188
       disk          185
pa     disk          185
mi     circle        184
az     sphere        184
oh     unknown       175
il     other         174
oh     disk          169
ca     rectangle     168
mi     disk          167
ca     chevron       167
       flash         166
pa     sphere        165
ca     diamond       165
il     sphere        163
oh     other         160
mi     unknown       157
az     disk          154
ca     cylinder      144
mi     other         142
pa     oval          141
fl     nan           136
mi     sphere        135
az     formation     131
fl     formation     131
il     oval          130
wa     formation     130
oh     oval          128
az     oval          124
tx     cigar         121
fl     changing      119
tx     formation     116
il     formation     109
tx     changing      109
ca     egg           107
mi     oval          102
wa     changing       98
ny     formation      98
fl     cigar          97
pa     formation      97
ny     cigar          96
az     nan            93
mi     nan            92
ny     nan            92
wa     flash          88
pa     nan            84
az     changing       84
ca     teardrop       84
il     nan            83
oh     formation      81
tx     nan            81
ny     changing       81
pa     cigar          80
fl     rectangle      74
       cylinder       74
tx     rectangle      74
wa     cigar          72
tx     cylinder       71
fl     flash          71
tx     flash          70
mi     formation      70
wa     rectangle      66
oh     cigar          66
fl     diamond        66
il     changing       65
tx     diamond        63
wa     cylinder       63
oh     changing       63
il     cigar          62
ny     flash          62
az     cigar          58
fl     chevron        57
ny     rectangle      56
tx     chevron        56
wa     diamond        55
ny     diamond        55
       cylinder       50
mi     cigar          50
wa     chevron        49
ny     egg            49
pa     changing       48
ny     chevron        48
mi     changing       48
il     rectangle      47
az     cylinder       46
       flash          46
pa     rectangle      44
oh     diamond        44
       cylinder       44
tx     teardrop       43
oh     rectangle      43
fl     egg            42
il     flash          42
fl     teardrop       41
oh     nan            41
az     rectangle      41
ny     teardrop       40
wa     egg            40
mi     rectangle      40
pa     cylinder       39
       diamond        37
il     cylinder       37
oh     flash          37
ca     cone           36
tx     egg            36
il     diamond        35
ca     cross          35
az     diamond        35
mi     diamond        34
az     chevron        34
il     egg            33
pa     flash          33
wa     teardrop       31
il     chevron        30
mi     cylinder       29
       flash          29
az     teardrop       27
pa     egg            27
       teardrop       26
az     egg            25
oh     teardrop       24
       egg            24
il     teardrop       22
mi     teardrop       20
oh     chevron        19
mi     egg            18
wa     cone           18
oh     cone           18
pa     chevron        17
       cone           17
ny     cross          17
az     cone           15
fl     cone           14
       cross          13
mi     chevron        12
tx     cone           12
ny     cone           11
mi     cone           10
wa     cross           9
oh     cross           9
az     cross           8
tx     cross           8
il     cone            8
pa     cross           7
il     cross           5
mi     cross           5
wa     delta           2
pa     dome            1
ca     flare           1
pa     hexagon         1
tx     delta           1
pa     round           1
ca     round           1
Name: count, dtype: int64


### (5pts) Part 1e: Observations and conclusions

In 3–6 sentences, summarize data quality and distributional patterns; reference at least one artifact from 1d.

users frequently left columns blank\
few sightings before 1995, and very few before 1950\
most sightings in the US\
much of the less common free response data (like shape) could be classified as more common labels \(round, circle, sphere|triangle,delta|light,fireball|unknown,other)


### (5pts) Part 1e: Next steps

Propose 2–3 concrete next steps (e.g., better deduplication with fuzzy text, geospatial clustering, normalization of duration text, timezone handling) to improve the quality of the data before moving on to some downstream tasks (you don't need to implement these).

I think our chosen buckets for duration(s) represent the data well, with the bulk of our data between 1m-30m (in two buckets) then 0s-1m (in two buckets).\
Combining labels for shapes and checking accuracy of longitude and latitude against location data would improve the quality of our data.\
uniform representation of time (implemented) was important as well as we list times as both 24:00 and 00:00 which pandas could not handle.


### (10 points) Part 1 f: Scalable & Structured Patterns

Now let's explore **network**, **geospatial**, and **time** patterns to dig a little deeper into our data.
Complete **any two** sub‑tasks below with **pandas**. For each you should provide your code, the ouput, plus some written analysis of what you find.


#### Sub-task 1. Co‑witness graph (space‑time co‑occurrence)
Bucket by geocell (`lat1=round(latitude,1)`, `lon1=round(longitude,1)`) and `datetime` floored to 15 minutes.  
Two reports in the same bucket are co‑witnessed. Build edges between reports in each bucket and summarize the graph (top buckets, approximate largest component).


#### Sub-task 2.  Geospatial hotspots
Aggregate by (`lat1`,`lon1`) and list **top‑20** cells. Optionally justify a normalization (per capita proxies or surface area) if you apply one.

In [ ]:
ufo_loc = ufo_fe[['country', 'state', 'city', 'latitude', 'longitude']].copy()

import numpy as np

# Haversine distance in miles
def haversine(lat1, lon1, lat2, lon2):
    R = 3958.8  # Radius of Earth in miles
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    return 2 * R * np.arcsin(np.sqrt(a))

def fill_lat_long_within_radius(group, max_miles=10):
    known = group.dropna(subset=['latitude', 'longitude'])
    missing = group[group['latitude'].isna() | group['longitude'].isna()]

    if len(known) == 0 or len(missing) == 0:
        return group  # Nothing to fill or no knowns

    # Compute pairwise distances between known points
    coords = known[['latitude', 'longitude']].to_numpy()
    too_far = False
    for i in range(len(coords)):
        for j in range(i + 1, len(coords)):
            dist = haversine(*coords[i], *coords[j])
            if dist > max_miles:
                too_far = True
                break
        if too_far:
            break

    if too_far:
        return group  # Skip group due to too much spread

    # Fill missing values with average of known values
    avg_lat = known['latitude'].mean()
    avg_lon = known['longitude'].mean()

    group['latitude'] = group['latitude'].fillna(avg_lat)
    group['longitude'] = group['longitude'].fillna(avg_lon)
    return group


ufo_loc = ufo_loc.groupby(['city', 'state'], dropna=False).apply(fill_lat_long_within_radius, max_miles=10).reset_index(drop=True)
ufo_loc = ufo_loc.dropna(subset=['latitude', 'longitude']).reset_index(drop=True)

ufo_loc['loc'] = ufo_loc[['latitude', 'longitude']].apply(tuple, axis=1)
display(ufo_loc[:20])

C:\Users\nick2\AppData\Local\Temp\ipykernel_64632\3842061845.py:45: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ufo_loc = ufo_loc.groupby(['city', 'state'], dropna=False).apply(fill_lat_long_within_radius, max_miles=10).reset_index(drop=True)

,country,state,city,latitude,longitude,loc
0,nan,nan,&ccedil;anakkale (turkey),40.155312,26.414160,"(40.155312, 26.41416)"
1,nan,nan,&iacute;safj&ouml;r&eth;ur (iceland),66.075833,-23.126667,"(66.075833, -23.126667)"
2,nan,nan,&ouml;lmstad (sweden),57.933333,14.366667,"(57.933333, 14.366667)"
3,us,co,1-25 corridor (southbound&#44 65 miles north n...,39.792716,-105.083267,"(39.792716, -105.083267)"
4,ca,bc,100 mile (canada),51.643970,-121.295010,"(51.64397, -121.29501)"
5,ca,bc,100 mile house (canada),51.643970,-121.295010,"(51.64397, -121.29501)"
6,us,ca,29 palms,34.135558,-116.054169,"(34.135558, -116.054169)"
7,us,ca,29 palms,34.135558,-116.054169,"(34.135558, -116.054169)"
8,us,ca,29 palms,34.135558,-116.054169,"(34.135558, -116.054169)"
9,ca,bc,70 mile house (canada),51.303136,-121.395769,"(51.303136, -121.395769)"
10,us,ms,?,32.354668,-89.398528,"(32.354668, -89.398528)"
11,us,ok,??,35.007752,-97.092877,"(35.007752, -97.092877)"
12,us,va,??,37.431573,-78.656894,"(37.431573, -78.656894)"
13,us,pa,a field outside small town,41.203322,-77.194525,"(41.203322, -77.194525)"
14,nan,nan,a55 northope (uk/north wales),53.213147,-3.133831,"(53.213147, -3.133831)"
15,de,nan,aachen (near cologne) (germany),50.770833,6.105278,"(50.770833, 6.105278)"
16,nan,nan,aalborg (denmark),57.048820,9.921747,"(57.04882, 9.921747)"
17,nan,nan,aalborg (denmark),57.048820,9.921747,"(57.04882, 9.921747)"
18,nan,nan,aalst (belgium),50.937810,4.040952,"(50.93781, 4.040952)"
19,au,nan,aandurah (western australia),-32.536809,115.742746,"(-32.536809, 115.742746)"

I set null lat/long to the average of values with identical city and state columns using haversine distance (suggested by gpt) to only trust that average if all the location data of identical city/states are within 10mi.
Depending what we want to do with this data, dropping ['us_only']=0 may be a good idea. Compared to the bulk of us data, other countries are barely represented.


#### Sub-task 3.  Shape × color co‑occurrence
Extract color keywords from `comments` (red/orange/yellow/green/blue/purple/violet/white/black/silver/gold/pink; handle “-ish” variants). Build a co‑occurrence table with `shape` or your normalized `shape_norm`. Interpret one pairing.

In [ ]:
# Define mapping groups
shape_map = {
    'light': 'light',
    'fireball': 'light',
    'flash': 'light',
    'flare': 'light',

    'unknown': 'nan',
    'other': 'nan',
    'nan': 'nan',   # in case 'nan' is a string

    'circle': 'round',
    'disk': 'round',
    'round': 'round',
    'sphere': 'round',
    'oval': 'round',
    'egg': 'round',
    'dome': 'round',
    'cone': 'round',
    'cylinder': 'round',
    'cigar': 'round',

    'triangle': 'polygon',
    'delta': 'polygon',
    'chevron': 'polygon',
    'rectangle': 'polygon',
    'diamond': 'polygon',
    'pyramid': 'polygon',
    'hexagon': 'polygon',
    'cross': 'polygon',
    'teardrop': 'polygon',
    'crescent': 'polygon',

    'changing': 'changing',
    'changed': 'changing',
    'formation': 'changing',
}

# Apply mapping
ufo_fe['shape_norm'] = ufo_fe['shape'].map(shape_map)
ufo_fe['shape_norm'] = ufo_fe['shape_norm'].fillna('nan')

colors = ["red","orange","yellow","green","blue",
          "purple","violet","white","black",
          "silver","gold","pink"]

# Match color at word boundary, allowing ish/y suffix
pattern = r'\b(' + '|'.join(colors) + r')(?:ish|y)?\b'

def extract_color(text):
    if pd.isna(text):
        return None
    match = re.search(pattern, str(text), flags=re.IGNORECASE)
    if match:
        return match.group(1).lower()  # base color
    return None

ufo_fe['color'] = ufo_fe['comments'].apply(extract_color)

In [ ]:
# Cross-tab between color and shape_norm
cooc = pd.crosstab(ufo_fe['color'], ufo_fe['shape_norm'], margins=True, margins_name='Total')
print(cooc)

shape_norm  changing  light   nan  polygon  round  Total
color
black            101     46   326      845    542   1860
blue              89    882   417      255    833   2476
gold              16     40    39       37     94    226
green             70   1275   437      241    826   2849
orange           420   3068   791      651   2809   7739
pink               8     40    27       38     60    173
purple             3     26    18       16     34     97
red              380   2297  1049      848   1915   6489
silver            45     53   187      103   1115   1503
violet             1      5     2        2      6     16
white            306   2178  1024      924   2229   6661
yellow            75    439   226      146    450   1336
Total           1514  10349  4543     4106  10913  31425

light and round columns contain similar occurances but light is only slightly weighted in colors like red|orange|green over round while round contains more white|yellow and almost all silver data.


#### Sub-task 4. Spatio‑temporal spikes (anomaly cues)
For each geocell, create a daily count series; compute z‑scores within cell; list top‑10 spikes across all cells. Discuss plausible causes.

## (40 points) Part 2: Association Rules in Movie Rating Behaviors

For the second part of this homework, we're going to examine movies using our understanding of association rules, to find movies that "go together". For this part, you will implement the apriori algorithm, and apply it to a movie rating dataset. We'll use the [MovieLens](https://grouplens.org/datasets/movielens/) dataset.

First, run the next cell to load the dataset we are going to use.

In [ ]:
import urllib3
import zipfile

http = urllib3.PoolManager()
req = http.request("GET", "https://files.grouplens.org/datasets/movielens/ml-latest-small.zip", preload_content=False)

with open("movie.zip", 'wb') as out:
  while True:
    data = req.read(4096)
    if not data:
      break
    out.write(data)
req.release_conn()

zFile = zipfile.ZipFile("movie.zip", "r")
for fileM in zFile.namelist():
  zFile.extract(fileM)

In [ ]:
# !ls ml-latest-small/

In this dataset, there are four columns: `userId` is the integer ids of users, `movieId` is the integer ids of movies, `rating` is the rate of the user gives to the movie, and `timestamp` which we do not use here. Each row denotes that the user of given `userId` rated the movie of the given `movieId`. We are going to treat each user as a "basket", so you will need to collect all the movies that have been rated by a single user as a basket.

Now, you need to implement the apriori algorithm and apply it to this dataset to find association rules of user rating behaviors where:

1. Define `rating` >= 3 is "like" (that is, only consider movie ratings of 3 or higher in your baskets; you may ignore all others)
2. `minsup` == 40 (out of 600 users/baskets); we may adjust this based on the discussion on Canvas
3. `minconf` == to be determined by a discussion on Canvas. You may try several different choices, but we will converge on a good choice for everyone for the final submission.

We know there are many existing implementations of apriori online (check github for some good starting points). You are welcome to read existing codebases and let that inform your approach. Do not copy-paste any existing code. We want your code to have sufficient comments to explain your steps, to show us that you really know what you are doing. Furthermore, you should add print statements to print out the intermediate steps of your method -- e.g., the size of the candidate set at each step of the method, the size of the filtered set, and any other important information you think will highlight the method.

To help get you started, we can load the ratings with the following code snippet:

In [ ]:
import pandas as pd
# read user ratings
allRatings = pd.read_csv("ml-latest-small/ratings.csv")
allRatings.columns

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

In [ ]:
likes_df = (
    allRatings[allRatings['rating'] >= 3.0]
    .groupby('userId')['movieId']
    .apply(list)
    .reset_index()
    .rename(columns={'movieId': 'likes'})
)
display(likes_df.head())

   userId                                              likes
0       1  [1, 3, 6, 47, 50, 70, 101, 110, 151, 157, 163,...
1       2  [318, 333, 1704, 3578, 6874, 8798, 46970, 4851...
2       3  [849, 1275, 1371, 1587, 2288, 2851, 3024, 3703...
3       4  [21, 45, 52, 58, 106, 125, 162, 171, 176, 215,...
4       5  [1, 21, 34, 36, 39, 50, 58, 110, 150, 153, 232...

### (15pts) Step 1: Implement Apriori Algorithm
In this section, you need to implement the Apriori algorithm, we will check the correctness of your code and we encourage efficient implementation.

In [ ]:
import itertools

def candid(F, transactions, minsup, k):
    Fk = dict()
    if k == 1: # Size 1 baskets
        for _, t in transactions.iterrows():
            for i in t['likes']: # create value counts for each movie
                if i in Fk.keys(): Fk[i] += 1
                else: Fk[i] = 1
        # drop movies that don't meet minsup
        Fk = {i: sup for i, sup in Fk.items() if sup >= minsup}
        return Fk
    if k == 2: # Size 2 baskets
        # itertools will create all possible pairs of frequent 1-itemsets
        # but this wont be effective for larger baskets since we want to only add possible candidates by appending 1 item from other candidates at a time
        candidates = list(itertools.combinations(F[k-2].keys(), 2))
    else:
        # --- General case: extend (k-1)-itemsets by one new item ---
        S = set()
        for key in F[k-2].keys():
            S.update(key)
        candidates = set()
        for key in F[k-2].keys():
            base = key
            for item in S:
                if item not in base:
                    new_cand = tuple(sorted(base + (item,)))
                    # keep only if all (k-1)-subsets are frequent
                    valid = True
                    for subset in itertools.combinations(new_cand, k-1):
                        if subset not in F[k-2]:
                            valid = False
                            break
                    if valid:
                        candidates.add(new_cand)

    # Count support
    if k >= 2:
        for _, t in transactions.iterrows():
            likes = set(t['likes'])
            for c in candidates:
                if set(c).issubset(likes):
                    Fk[c] = Fk.get(c, 0) + 1
        return {c: sup for c, sup in Fk.items() if sup >= minsup}


def Apriori(transactions, minsup, muted=False):
    k = 1
    F = []
    F.append(candid(F, transactions, minsup, k))
    if not muted: print(f'Found {len(F[k - 1])} frequent {k}-itemsets')
    while F[k - 1]:
        k += 1
        F.append(candid(F, transactions, minsup, k))
        if not muted: print(f'Found {len(F[k - 1])} frequent {k}-itemsets')
    return F

Ab4I = Apriori(likes_df, minsup=60)

Found 259 frequent 1-itemsets
Found 2856 frequent 2-itemsets
Found 4689 frequent 3-itemsets
Found 4252 frequent 4-itemsets
Found 1849 frequent 5-itemsets
Found 378 frequent 6-itemsets
Found 30 frequent 7-itemsets
Found 1 frequent 8-itemsets
Found 0 frequent 9-itemsets

In [ ]:
print(Ab4I)

[{1: 199, 6: 99, 47: 191, 50: 197, 110: 218, 223: 94, 231: 88, 235: 62, 260: 234, 296: 287, 316: 119, 349: 102, 356: 315, 367: 122, 457: 182, 480: 216, 500: 121, 527: 205, 590: 152, 592: 172, 593: 263, 608: 171, 648: 145, 733: 112, 736: 93, 780: 164, 919: 83, 923: 62, 1073: 112, 1080: 78, 1089: 124, 1097: 105, 1136: 126, 1196: 199, 1197: 135, 1198: 191, 1206: 109, 1208: 101, 1210: 185, 1213: 122, 1214: 130, 1220: 78, 1222: 96, 1240: 120, 1258: 102, 1265: 133, 1270: 159, 1278: 63, 1291: 135, 1517: 84, 1573: 60, 1580: 139, 1617: 92, 1625: 63, 1676: 62, 1732: 95, 2000: 71, 2012: 71, 2028: 179, 2115: 97, 2174: 78, 2291: 74, 2329: 127, 2502: 88, 2542: 65, 2571: 257, 2628: 97, 2692: 72, 2700: 69, 2716: 109, 2797: 83, 2858: 186, 2916: 81, 2959: 206, 2987: 85, 2997: 91, 3052: 66, 3147: 106, 3578: 153, 3793: 121, 318: 313, 1704: 136, 6874: 123, 48516: 103, 58559: 144, 68157: 85, 74458: 60, 79132: 129, 91529: 71, 99114: 65, 109487: 70, 21: 77, 357: 86, 368: 67, 588: 169, 595: 137, 904: 81, 912: 95, 1219: 78, 1225: 74, 1259: 89, 1288: 63, 1923: 95, 1968: 98, 2683: 88, 2762: 158, 2791: 79, 3408: 60, 3897: 78, 3996: 98, 4027: 84, 4034: 64, 4896: 96, 34: 104, 36: 63, 39: 87, 150: 185, 153: 96, 253: 96, 300: 74, 344: 112, 364: 162, 410: 66, 474: 68, 589: 210, 594: 71, 597: 120, 2: 89, 10: 118, 11: 60, 16: 75, 17: 61, 25: 63, 32: 171, 62: 70, 104: 81, 141: 78, 161: 94, 165: 127, 185: 82, 208: 74, 292: 90, 293: 129, 317: 65, 329: 97, 337: 68, 339: 88, 377: 146, 380: 154, 434: 77, 440: 68, 454: 92, 539: 94, 587: 97, 750: 94, 924: 94, 1101: 62, 1584: 68, 1610: 85, 1682: 114, 1917: 65, 3114: 91, 4306: 153, 4886: 125, 4963: 110, 4993: 183, 4995: 117, 5218: 76, 5349: 106, 5445: 107, 5618: 83, 5816: 87, 5952: 174, 5989: 106, 6333: 66, 6365: 74, 6539: 133, 7143: 61, 7153: 174, 8360: 79, 8636: 72, 8665: 69, 8961: 117, 32587: 76, 49272: 75, 586: 84, 2011: 72, 5378: 68, 1247: 73, 1307: 78, 1784: 87, 6377: 134, 33794: 103, 51662: 72, 54286: 71, 68954: 99, 1721: 111, 4011: 90, 288: 71, 858: 178, 1200: 112, 1527: 100, 1653: 81, 3949: 86, 4022: 89, 7438: 101, 33493: 62, 48774: 60, 48780: 84, 50872: 67, 60069: 95, 72998: 79, 111: 100, 541: 114, 1193: 129, 1201: 68, 4226: 149, 4878: 98, 4973: 113, 7361: 123, 48394: 74, 1036: 134, 1221: 124, 2194: 61, 6016: 72, 442: 61, 778: 96, 1246: 79, 1356: 84, 1961: 89, 2324: 80, 2706: 78, 2918: 101, 3751: 67, 4262: 61, 5418: 100, 7147: 63, 8368: 87, 44191: 94, 45722: 60, 46578: 68, 59315: 88, 69122: 67, 89745: 61, 551: 83, 1079: 62, 2355: 83, 2396: 79, 2617: 61, 1028: 65, 3948: 69, 40815: 67, 63082: 61, 6711: 71, 35836: 63, 1393: 75, 1387: 85, 3481: 67, 8874: 70}, {(1, 47): 81, (1, 50): 86, (1, 110): 100, (1, 260): 116, (1, 296): 121, (1, 356): 136, (1, 367): 70, (1, 457): 85, (1, 480): 111, (1, 500): 66, (1, 527): 82, (1, 590): 72, (1, 592): 83, (1, 593): 107, (1, 608): 88, (1, 648): 90, (1, 733): 65, (1, 780): 100, (1, 1073): 75, (1, 1097): 64, (1, 1136): 76, (1, 1196): 98, (1, 1197): 74, (1, 1198): 95, (1, 1210): 102, (1, 1213): 60, (1, 1214): 66, (1, 1240): 67, (1, 1265): 86, (1, 1270): 92, (1, 1291): 80, (1, 1580): 80, (1, 2028): 85, (1, 2115): 63, (1, 2571): 103, (1, 2716): 67, (1, 2858): 79, (1, 2959): 85, (1, 3578): 69, (1, 3793): 63, (6, 47): 63, (6, 50): 65, (6, 110): 66, (6, 260): 66, (6, 296): 71, (6, 356): 71, (6, 457): 66, (6, 593): 72, (6, 608): 63, (47, 50): 112, (47, 110): 122, (47, 260): 104, (47, 296): 158, (47, 316): 63, (47, 356): 142, (47, 367): 71, (47, 457): 101, (47, 480): 110, (47, 500): 66, (47, 527): 99, (47, 590): 84, (47, 592): 93, (47, 593): 140, (47, 608): 98, (47, 648): 78, (47, 780): 78, (47, 1089): 89, (47, 1136): 71, (47, 1196): 95, (47, 1197): 66, (47, 1198): 89, (47, 1206): 67, (47, 1210): 88, (47, 1213): 75, (47, 1214): 70, (47, 1222): 60, (47, 1240): 68, (47, 1258): 63, (47, 1265): 71, (47, 1270): 75, (47, 1291): 71, (47, 1580): 64, (47, 1732): 63, (47, 2028): 86, (47, 2115): 60, (47, 2329): 82, (47, 2571): 121, (47, 2858): 100, (47, 2959): 110, (47, 2997): 60, (47, 3147): 60, (47, 3578): 82, (47, 3793): 61, (50, 110): 98, (50, 223): 61, (50, 260): 108, (50, 296): 155, (50, 356): 141, (50, 367): 66, (50, 457): 88, (50, 480): 97, (50, 527): 111, (50, 590): 74, (50, 592): 88, (50, 593): 130, (50, 608): 108, (50, 648): 68, (50, 780): 74, (50, 1089): 93, (50, 1136): 73, (50, 1196): 100, (50, 1197): 70, (50, 1198): 95, (50, 1206): 68, (50, 1208): 70, (50, 1210): 90, (50, 1213): 91, (50, 1214): 68, (50, 1222): 67, (50, 1240): 65, (50, 1258): 66, (50, 1265): 74, (50, 1270): 80, (50, 1291): 66, (50, 1580): 61, (50, 1617): 62, (50, 1732): 64, (50, 2028): 88, (50, 2329): 81, (50, 2571): 114, (50, 2858): 100, (50, 2959): 111, (50, 2997): 62, (50, 3578): 79, (110, 260): 107, (110, 296): 155, (110, 316): 88, (110, 349): 74, (110, 356): 165, (110, 367): 78, (110, 457): 124, (110, 480): 141, (110, 500): 69, (110, 527): 106, (110, 590): 108, (110, 592): 114, (110, 593): 137, (110, 608): 85, (110, 648): 82, (110, 733): 63, (110, 780): 87, (110, 1089): 65, (110, 1196): 97, (110, 1197): 64, (110, 1198): 85, (110, 1210): 101, (110, 1213): 62, (110, 1214): 69, (110, 1240): 74, (110, 1265): 67, (110, 1270): 74, (110, 1291): 77, (110, 1580): 73, (110, 2028): 107, (110, 2329): 66, (110, 2571): 121, (110, 2858): 81, (110, 2959): 93, (110, 3147): 62, (110, 3578): 84, (223, 296): 76, (223, 356): 64, (223, 593): 64, (231, 296): 68, (231, 356): 72, (231, 480): 60, (260, 296): 137, (260, 356): 144, (260, 367): 63, (260, 457): 86, (260, 480): 119, (260, 527): 101, (260, 590): 68, (260, 592): 85, (260, 593): 136, (260, 608): 112, (260, 648): 97, (260, 733): 80, (260, 780): 108, (260, 919): 65, (260, 1073): 78, (260, 1089): 88, (260, 1097): 80, (260, 1136): 94, (260, 1196): 176, (260, 1197): 98, (260, 1198): 146, (260, 1206): 73, (260, 1208): 73, (260, 1210): 161, (260, 1213): 85, (260, 1214): 95, (260, 1222): 73, (260, 1240): 98, (260, 1258): 67, (260, 1265): 100, (260, 1270): 114, (260, 1291): 112, (260, 1517): 65, (260, 1580): 99, (260, 1617): 66, (260, 1732): 67, (260, 2028): 117, (260, 2115): 82, (260, 2329): 75, (260, 2571): 161, (260, 2628): 84, (260, 2716): 83, (260, 2797): 62, (260, 2858): 112, (260, 2916): 69, (260, 2959): 117, (260, 2987): 61, (260, 2997): 67, (260, 3147): 70, (260, 3578): 100, (260, 3793): 90, (296, 316): 77, (296, 349): 72, (296, 356): 207, (296, 367): 85, (296, 457): 124, (296, 480): 145, (296, 500): 81, (296, 527): 137, (296, 590): 115, (296, 592): 124, (296, 593): 188, (296, 608): 132, (296, 648): 88, (296, 733): 62, (296, 780): 98, (296, 1073): 68, (296, 1080): 63, (296, 1089): 108, (296, 1097): 70, (296, 1136): 92, (296, 1196): 127, (296, 1197): 84, (296, 1198): 115, (296, 1206): 84, (296, 1208): 80, (296, 1210): 112, (296, 1213): 105, (296, 1214): 80, (296, 1222): 79, (296, 1240): 85, (296, 1258): 79, (296, 1265): 91, (296, 1270): 99, (296, 1291): 91, (296, 1580): 84, (296, 1617): 66, (296, 1732): 82, (296, 2028): 117, (296, 2115): 70, (296, 2329): 105, (296, 2502): 67, (296, 2571): 160, (296, 2628): 60, (296, 2716): 76, (296, 2858): 131, (296, 2959): 145, (296, 2997): 73, (296, 3147): 73, (296, 3578): 95, (296, 3793): 65, (316, 356): 88, (316, 457): 79, (316, 480): 84, (316, 590): 71, (316, 592): 80, (316, 593): 73, (316, 780): 61, (349, 356): 85, (349, 457): 91, (349, 480): 75, (349, 590): 75, (349, 592): 73, (349, 593): 72, (356, 367): 96, (356, 457): 138, (356, 480): 177, (356, 500): 113, (356, 527): 155, (356, 590): 124, (356, 592): 126, (356, 593): 183, (356, 608): 112, (356, 648): 102, (356, 733): 71, (356, 780): 114, (356, 1073): 67, (356, 1089): 90, (356, 1097): 82, (356, 1136): 88, (356, 1196): 133, (356, 1197): 95, (356, 1198): 114, (356, 1206): 81, (356, 1208): 72, (356, 1210): 131, (356, 1213): 89, (356, 1214): 82, (356, 1222): 75, (356, 1240): 87, (356, 1258): 78, (356, 1265): 106, (356, 1270): 124, (356, 1291): 96, (356, 1517): 64, (356, 1580): 106, (356, 1617): 65, (356, 1732): 74, (356, 2012): 63, (356, 2028): 129, (356, 2115): 78, (356, 2291): 61, (356, 2329): 90, (356, 2502): 68, (356, 2571): 173, (356, 2628): 76, (356, 2716): 85, (356, 2797): 64, (356, 2858): 124, (356, 2916): 62, (356, 2959): 143, (356, 2987): 62, (356, 2997): 67, (356, 3147): 89, (356, 3578): 111, (356, 3793): 80, (367, 457): 75, (367, 480): 89, (367, 500): 66, (367, 590): 61, (367, 592): 83, (367, 593): 79, (367, 780): 62, (457, 480): 131, (457, 500): 74, (457, 527): 91, (457, 590): 101, (457, 592): 109, (457, 593): 131, (457, 608): 80, (457, 648): 79, (457, 733): 67, (457, 780): 77, (457, 1136): 60, (457, 1196): 82, (457, 1197): 63, (457, 1198): 77, (457, 1210): 78, (457, 1214): 63, (457, 1240): 66, (457, 1265): 63, (457, 1270): 65, (457, 1291): 65, (457, 1580): 62, (457, 2028): 76, (457, 2571): 88, (457, 2858): 61, (480, 500): 93, (480, 527): 100, (480, 590): 111, (480, 592): 117, (480, 593): 140, (480, 608): 87, (480, 648): 98, (480, 733): 71, (480, 736): 61, (480, 780): 111, (480, 1073): 61, (480, 1089): 66, (480, 1097): 69, (480, 1136): 69, (480, 1196): 111, (480, 1197): 74, (480, 1198): 104, (480, 1210): 113, (480, 1213): 65, (480, 1214): 73, (480, 1240): 84, (480, 1265): 81, (480, 1270): 94, (480, 1291): 88, (480, 1580): 89, (480, 2028): 95, (480, 2115): 70, (480, 2571): 112, (480, 2628): 63, (480, 2716): 68, (480, 2858): 87, (480, 2959): 80, (480, 3578): 77, (480, 3793): 67, (500, 527): 62, (500, 590): 64, (500, 592): 72, (500, 593): 76, (500, 780): 60, (527, 590): 81, (527, 592): 70, (527, 593): 137, (527, 608): 87, (527, 648): 68, (527, 780): 73, (527, 1089): 66, (527, 1097): 64, (527, 1136): 63, (527, 1196): 95, (527, 1197): 61, (527, 1198): 81, (527, 1206): 62, (527, 1208): 61, (527, 1210): 83, (527, 1213): 67, (527, 1214): 63, (527, 1265): 73, (527, 1270): 73, (527, 1291): 60, (527, 1580): 63, (527, 2028): 106, (527, 2329): 72, (527, 2571): 118, (527, 2858): 90, (527, 2959): 109, (527, 3147): 68, (527, 3578): 69, (590, 592): 97, (590, 593): 104, (590, 648): 63, (590, 780): 65, (590, 1196): 64, (590, 1210): 61, (590, 2571): 60, (592, 593): 111, (592, 608): 65, (592, 648): 73, (592, 780): 79, (592, 1196): 81, (592, 1198): 73, (592, 1210): 76, (592, 1240): 64, (592, 1265): 60, (592, 1270): 67, (592, 1291): 69, (592, 1580): 63, (592, 2028): 64, (592, 2115): 60, (592, 2571): 72, (593, 608): 121, (593, 648): 85, (593, 733): 63, (593, 780): 90, (593, 919): 64, (593, 1073): 60, (593, 1089): 89, (593, 1097): 72, (593, 1136): 86, (593, 1196): 126, (593, 1197): 81, (593, 1198): 113, (593, 1206): 75, (593, 1208): 71, (593, 1210): 110, (593, 1213): 93, (593, 1214): 87, (593, 1222): 64, (593, 1240): 81, (593, 1258): 79, (593, 1265): 86, (593, 1270): 94, (593, 1291): 84, (593, 1580): 81, (593, 1617): 64, (593, 1732): 63, (593, 2028): 111, (593, 2115): 62, (593, 2329): 84, (593, 2571): 141, (593, 2716): 66, (593, 2858): 119, (593, 2959): 127, (593, 2997): 64, (593, 3147): 78, (593, 3578): 87, (593, 3793): 63, (608, 648): 67, (608, 780): 69, (608, 1073): 60, (608, 1089): 88, (608, 1136): 84, (608, 1196): 98, (608, 1197): 79, (608, 1198): 97, (608, 1206): 73, (608, 1208): 73, (608, 1210): 93, (608, 1213): 86, (608, 1214): 72, (608, 1222): 62, (608, 1240): 66, (608, 1258): 67, (608, 1265): 81, (608, 1270): 74, (608, 1291): 76, (608, 1580): 69, (608, 1617): 69, (608, 1732): 66, (608, 2028): 84, (608, 2329): 65, (608, 2571): 100, (608, 2858): 99, (608, 2959): 98, (608, 2997): 63, (608, 3578): 64, (648, 733): 74, (648, 736): 63, (648, 780): 100, (648, 1073): 62, (648, 1196): 80, (648, 1198): 67, (648, 1210): 88, (648, 1265): 61, (648, 1270): 68, (648, 1291): 64, (648, 1580): 66, (648, 2028): 69, (648, 2571): 79, (648, 2858): 63, (733, 780): 73, (733, 1196): 64, (733, 1198): 63, (733, 1210): 70, (733, 2571): 60, (736, 780): 69, (780, 1073): 66, (780, 1196): 91, (780, 1198): 80, (780, 1210): 97, (780, 1240): 68, (780, 1265): 64, (780, 1270): 77, (780, 1291): 63, (780, 1580): 75, (780, 2028): 78, (780, 2115): 61, (780, 2571): 89, (780, 2858): 61, (780, 2959): 63, (780, 3578): 66, (919, 1196): 61, (919, 1198): 61, (1073, 1196): 66, (1073, 1198): 60, (1073, 1210): 67, (1073, 2571): 61, (1080, 1136): 62, (1089, 1136): 64, (1089, 1196): 86, (1089, 1198): 80, (1089, 1206): 67, (1089, 1208): 71, (1089, 1210): 79, (1089, 1213): 82, (1089, 1214): 74, (1089, 1222): 69, (1089, 1240): 62, (1089, 1265): 64, (1089, 1270): 67, (1089, 1291): 68, (1089, 1617): 63, (1089, 1732): 63, (1089, 2028): 81, (1089, 2329): 70, (1089, 2571): 100, (1089, 2858): 88, (1089, 2959): 92, (1089, 3578): 67, (1097, 1196): 79, (1097, 1198): 70, (1097, 1210): 80, (1097, 1240): 60, (1097, 1265): 66, (1097, 1270): 74, (1097, 1291): 66, (1097, 1580): 62, (1097, 2028): 67, (1097, 2571): 76, (1097, 2858): 62, (1136, 1196): 91, (1136, 1197): 79, (1136, 1198): 90, (1136, 1208): 63, (1136, 1210): 78, (1136, 1213): 61, (1136, 1214): 67, (1136, 1240): 60, (1136, 1265): 74, (1136, 1270): 74, (1136, 1291): 72, (1136, 1580): 62, (1136, 2028): 66, (1136, 2571): 91, (1136, 2716): 62, (1136, 2858): 78, (1136, 2959): 82, (1136, 3578): 62, (1196, 1197): 98, (1196, 1198): 138, (1196, 1206): 67, (1196, 1208): 72, (1196, 1210): 153, (1196, 1213): 81, (1196, 1214): 98, (1196, 1222): 70, (1196, 1240): 99, (1196, 1258): 70, (1196, 1265): 90, (1196, 1270): 113, (1196, 1291): 112, (1196, 1517): 62, (1196, 1580): 94, (1196, 1617): 63, (1196, 1732): 69, (1196, 2028): 113, (1196, 2115): 83, (1196, 2329): 71, (1196, 2571): 157, (1196, 2628): 80, (1196, 2716): 84, (1196, 2797): 63, (1196, 2858): 102, (1196, 2916): 70, (1196, 2959): 107, (1196, 2987): 64, (1196, 2997): 60, (1196, 3147): 64, (1196, 3578): 98, (1196, 3793): 85, (1197, 1198): 97, (1197, 1210): 85, (1197, 1213): 65, (1197, 1214): 60, (1197, 1240): 61, (1197, 1265): 79, (1197, 1270): 85, (1197, 1291): 73, (1197, 1580): 66, (1197, 2028): 72, (1197, 2571): 91, (1197, 2716): 60, (1197, 2858): 72, (1197, 2959): 75, (1197, 3578): 60, (1198, 1206): 63, (1198, 1208): 60, (1198, 1210): 120, (1198, 1213): 76, (1198, 1214): 88, (1198, 1222): 60, (1198, 1240): 90, (1198, 1258): 65, (1198, 1265): 90, (1198, 1270): 110, (1198, 1291): 120, (1198, 1580): 83, (1198, 1732): 60, (1198, 2028): 103, (1198, 2115): 84, (1198, 2329): 62, (1198, 2571): 139, (1198, 2628): 64, (1198, 2716): 80, (1198, 2858): 95, (1198, 2959): 99, (1198, 2997): 64, (1198, 3578): 94, (1198, 3793): 75, (1206, 1210): 63, (1206, 2028): 60, (1206, 2571): 80, (1206, 2858): 81, (1206, 2959): 83, (1208, 1210): 62, (1208, 1213): 64, (1208, 1222): 63, (1208, 2028): 64, (1208, 2571): 70, (1208, 2858): 65, (1208, 2959): 65, (1210, 1213): 70, (1210, 1214): 87, (1210, 1222): 65, (1210, 1240): 94, (1210, 1258): 61, (1210, 1265): 89, (1210, 1270): 110, (1210, 1291): 107, (1210, 1517): 61, (1210, 1580): 93, (1210, 1732): 62, (1210, 2028): 110, (1210, 2115): 80, (1210, 2329): 62, (1210, 2571): 142, (1210, 2628): 78, (1210, 2716): 79, (1210, 2858): 96, (1210, 2916): 64, (1210, 2959): 92, (1210, 2987): 60, (1210, 3147): 61, (1210, 3578): 94, (1210, 3793): 85, (1213, 1214): 62, (1213, 1222): 61, (1213, 1240): 60, (1213, 1258): 60, (1213, 1265): 62, (1213, 1270): 67, (1213, 1291): 63, (1213, 2028): 72, (1213, 2329): 70, (1213, 2571): 87, (1213, 2858): 81, (1213, 2959): 86, (1213, 3578): 61, (1214, 1240): 76, (1214, 1265): 63, (1214, 1270): 70, (1214, 1291): 77, (1214, 1580): 63, (1214, 2028): 78, (1214, 2115): 60, (1214, 2571): 98, (1214, 2858): 76, (1214, 2959): 73, (1214, 3578): 66, (1222, 2028): 67, (1222, 2571): 76, (1222, 2858): 65, (1222, 2959): 68, (1240, 1265): 66, (1240, 1270): 78, (1240, 1291): 82, (1240, 1580): 71, (1240, 2028): 83, (1240, 2115): 66, (1240, 2571): 104, (1240, 2716): 64, (1240, 2858): 73, (1240, 2916): 61, (1240, 2959): 69, (1240, 3578): 67, (1240, 3793): 62, (1258, 1270): 60, (1258, 2571): 72, (1258, 2858): 65, (1258, 2959): 75, (1265, 1270): 86, (1265, 1291): 76, (1265, 1580): 78, (1265, 2028): 80, (1265, 2115): 63, (1265, 2571): 98, (1265, 2716): 67, (1265, 2858): 80, (1265, 2959): 80, (1265, 2997): 63, (1265, 3578): 70, (1265, 3793): 61, (1270, 1291): 92, (1270, 1580): 80, (1270, 2012): 64, (1270, 2028): 85, (1270, 2115): 73, (1270, 2571): 110, (1270, 2716): 78, (1270, 2797): 63, (1270, 2858): 84, (1270, 2959): 82, (1270, 3578): 76, (1270, 3793): 69, (1291, 1580): 75, (1291, 2028): 86, (1291, 2115): 84, (1291, 2571): 108, (1291, 2716): 71, (1291, 2858): 76, (1291, 2959): 76, (1291, 3578): 75, (1291, 3793): 66, (1517, 2571): 62, (1580, 2028): 90, (1580, 2115): 71, (1580, 2571): 107, (1580, 2628): 64, (1580, 2716): 63, (1580, 2858): 74, (1580, 2959): 70, (1580, 3578): 71, (1580, 3793): 70, (1617, 2571): 65, (1617, 2858): 65, (1732, 2028): 61, (1732, 2571): 77, (1732, 2858): 67, (1732, 2959): 74, (2000, 2571): 61, (2028, 2115): 68, (2028, 2329): 75, (2028, 2571): 145, (2028, 2628): 68, (2028, 2716): 63, (2028, 2858): 99, (2028, 2916): 60, (2028, 2959): 106, (2028, 3147): 77, (2028, 3578): 96, (2028, 3793): 68, (2115, 2571): 81, (2115, 2716): 67, (2115, 2858): 61, (2115, 2959): 62, (2115, 3578): 61, (2329, 2571): 96, (2329, 2858): 89, (2329, 2959): 103, (2329, 3578): 67, (2502, 2571): 66, (2502, 2858): 63, (2502, 2959): 66, (2571, 2628): 84, (2571, 2716): 88, (2571, 2858): 131, (2571, 2916): 71, (2571, 2959): 158, (2571, 2987): 63, (2571, 2997): 75, (2571, 3147): 86, (2571, 3578): 123, (2571, 3793): 98, (2716, 2858): 66, (2716, 2959): 64, (2716, 3578): 65, (2858, 2959): 120, (2858, 2997): 71, (2858, 3147): 65, (2858, 3578): 88, (2858, 3793): 65, (2959, 2997): 68, (2959, 3147): 72, (2959, 3578): 103, (2959, 3793): 69, (3147, 3578): 60, (3578, 3793): 76, (3578, 318): 97, (3578, 1704): 75, (3578, 6874): 75, (3578, 48516): 64, (3578, 58559): 76, (3578, 79132): 63, (318, 1704): 107, (318, 6874): 93, (318, 48516): 85, (318, 58559): 105, (318, 68157): 61, (318, 79132): 97, (1704, 6874): 60, (1704, 58559): 60, (6874, 48516): 63, (6874, 58559): 77, (6874, 79132): 64, (48516, 58559): 72, (48516, 79132): 66, (58559, 68157): 63, (58559, 79132): 97, (58559, 91529): 67, (68157, 79132): 67, (79132, 91529): 60, (260, 588): 84, (260, 595): 61, (260, 912): 66, (260, 1259): 65, (260, 1923): 62, (260, 1968): 70, (260, 2683): 67, (260, 2762): 101, (260, 2791): 62, (260, 3996): 64, (260, 4896): 69, (457, 21): 65, (457, 588): 97, (457, 595): 78, (457, 2762): 68, (593, 357): 61, (593, 588): 98, (593, 595): 79, (593, 904): 60, (593, 912): 70, (593, 1219): 61, (593, 1259): 65, (593, 1923): 61, (593, 1968): 65, (593, 2762): 102, (608, 1219): 60, (608, 2762): 77, (648, 588): 71, (1073, 588): 60, (1136, 588): 60, (1136, 2762): 70, (1196, 588): 79, (1196, 912): 64, (1196, 1259): 63, (1196, 1923): 65, (1196, 1968): 70, (1196, 2683): 60, (1196, 2762): 100, (1196, 2791): 60, (1196, 3996): 64, (1196, 4896): 66, (1197, 588): 61, (1197, 2762): 67, (1198, 588): 68, (1198, 912): 61, (1198, 1259): 65, (1198, 1968): 65, (1198, 2762): 85, (1198, 3996): 63, (1213, 2762): 63, (1265, 588): 67, (1265, 1968): 61, (1265, 2762): 77, (1291, 588): 60, (1291, 2762): 71, (1517, 2683): 62, (1580, 588): 70, (1580, 2762): 78, (2858, 588): 60, (2858, 1923): 61, (2858, 1968): 66, (2858, 2762): 100, (2858, 3996): 61, (588, 595): 113, (1923, 2762): 61, (1, 318): 124, (1, 588): 95, (1, 595): 81, (1, 34): 68, (1, 150): 98, (1, 344): 60, (1, 364): 95, (1, 589): 91, (1, 597): 60, (50, 318): 156, (50, 588): 71, (50, 150): 85, (50, 364): 69, (50, 589): 98, (110, 318): 155, (110, 588): 93, (110, 595): 80, (110, 34): 61, (110, 150): 116, (110, 153): 69, (110, 253): 68, (110, 344): 66, (110, 364): 92, (110, 589): 140, (110, 597): 69, (296, 318): 209, (296, 21): 64, (296, 588): 109, (296, 595): 82, (296, 34): 69, (296, 150): 127, (296, 153): 66, (296, 253): 69, (296, 300): 64, (296, 344): 82, (296, 364): 104, (296, 589): 145, (296, 597): 79, (349, 318): 69, (349, 588): 64, (349, 150): 72, (349, 589): 71, (367, 318): 76, (367, 588): 77, (367, 595): 66, (367, 150): 63, (367, 364): 84, (367, 589): 80, (457, 318): 125, (457, 34): 71, (457, 150): 113, (457, 153): 61, (457, 253): 62, (457, 344): 66, (457, 364): 90, (457, 474): 62, (457, 589): 124, (457, 597): 73, (527, 318): 157, (527, 588): 72, (527, 595)

### (5pts) Step 2: Print Your Association Rules

Next you should print your final association rules in the following format:

**movie_name_1, movie_name_2, ... -->
movie_name_k**

where the movie names can be fetched by joining the movieId with the file `movies.csv`. For example, one rule that you might find is:

**Matrix, The (1999),  Star Wars: Episode V - The Empire Strikes Back (1980),  Star Wars: Episode IV - A New Hope (1977),  ->
Star Wars: Episode VI - Return of the Jedi (1983)**

In [ ]:
scores = dict()

for d in Ab4I[3:]: # length 4-8 baskets
    for k, v in d.items():
        for i in range(len(k)):
            ktemp = k[:i] + k[i+1:]
            conf = v/Ab4I[len(ktemp)-1][ktemp]
            inter = abs(v/len(likes_df) - Ab4I[0][k[i]]/len(likes_df))
            lift = v/(Ab4I[len(ktemp)-1][ktemp]*Ab4I[0][k[i]])
            scores[(ktemp, k[i])] = (v, conf, inter, lift)
for k,v in scores.items():
    print(k, v)

((1198, 1210, 2115), 1196) (72, 0.9863013698630136, 0.20853858784893267, 0.004956288290768913)
((1196, 1210, 2115), 1198) (72, 0.9113924050632911, 0.19540229885057472, 0.004771687984624561)
((1196, 1198, 2115), 1210) (72, 0.96, 0.18555008210180626, 0.005189189189189189)
((1196, 1198, 1210), 2115) (72, 0.6153846153846154, 0.04105090311986864, 0.006344171292624901)
((1210, 2571, 2959), 593) (64, 0.735632183908046, 0.3267651888341544, 0.002797080547178882)
((593, 2571, 2959), 1210) (64, 0.6153846153846154, 0.19868637110016424, 0.0033264033264033266)
((593, 1210, 2959), 2571) (64, 0.9552238805970149, 0.3169129720853859, 0.0037168244381206804)
((593, 1210, 2571), 2959) (64, 0.7191011235955056, 0.23316912972085385, 0.003490782153376241)
((356, 527, 1196), 296) (64, 0.810126582278481, 0.36617405582922824, 0.00282274070480307)
((296, 527, 1196), 356) (64, 0.8533333333333334, 0.41215106732348117, 0.002708994708994709)
((296, 356, 1196), 527) (64, 0.6153846153846154, 0.2315270935960591, 0.00300187617260788)
((296, 356, 527), 1196) (64, 0.5663716814159292, 0.22167487684729065, 0.0028460888513363275)
((356, 1196, 1291), 296) (70, 0.8641975308641975, 0.3563218390804598, 0.0030111412225233363)
((296, 1196, 1291), 356) (70, 0.8860759493670886, 0.4022988505747127, 0.0028129395218002813)
((296, 356, 1291), 1196) (70, 0.8860759493670886, 0.21182266009852216, 0.004452642961643661)
((296, 356, 1196), 1291) (70, 0.6730769230769231, 0.10673234811165846, 0.004985754985754986)
((593, 608, 1198), 356) (60, 0.7692307692307693, 0.41871921182266014, 0.002442002442002442)
((356, 608, 1198), 593) (60, 0.8108108108108109, 0.33333333333333337, 0.003082930839584832)
((356, 593, 1198), 608) (60, 0.7407407407407407, 0.18226600985221675, 0.004331817197314273)
((356, 593, 608), 1198) (60, 0.6818181818181818, 0.21510673234811167, 0.003569728700618753)
((593, 1198, 2028), 260) (62, 0.8857142857142857, 0.2824302134646962, 0.003785103785103785)
((260, 1198, 2028), 593) (62, 0.7209302325581395, 0.3300492610837439, 0.0027411795914758156)
((260, 593, 2028), 1198) (62, 0.7848101265822784, 0.2118226600985222, 0.004108953542315594)
((260, 593, 1198), 2028) (62, 0.6458333333333334, 0.1921182266009852, 0.003608007448789572)
((1196, 1580, 2028), 260) (69, 0.9583333333333334, 0.270935960591133, 0.004095441595441595)
((260, 1580, 2028), 1196) (69, 0.9324324324324325, 0.2134646962233169, 0.004685590112725791)
((260, 1196, 2028), 1580) (69, 0.6699029126213593, 0.11494252873563218, 0.004819445414542153)
((260, 1196, 1580), 2028) (69, 0.7840909090909091, 0.18062397372742198, 0.004380396140172676)
((1198, 1210, 2571), 356) (78, 0.7647058823529411, 0.3891625615763547, 0.002427637721755369)
((356, 1210, 2571), 1198) (78, 0.7222222222222222, 0.18555008210180624, 0.0037812681791739382)
((356, 1198, 2571), 1210) (78, 0.8297872340425532, 0.17569786535303777, 0.004485336400230017)
((356, 1198, 1210), 2571) (78, 0.8571428571428571, 0.2939244663382594, 0.0033351862145636463)
((593, 1198, 1210), 260) (75, 0.9615384615384616, 0.2610837438423645, 0.00410913872452334)
((260, 1198, 1210), 593) (75, 0.6521739130434783, 0.30870279146141216, 0.0024797487187964953)
((260, 593, 1210), 1198) (75, 0.78125, 0.19047619047619047, 0.004090314136125654)
((260, 593, 1198), 1210) (75, 0.78125, 0.180623973727422, 0.004222972972972973)
((1198, 2571, 2716), 1196) (60, 0.8571428571428571, 0.22824302134646962, 0.004307250538406317)
((1196, 2571, 2716), 1198) (60, 0.821917808219178, 0.21510673234811167, 0.0043032345980061676)
((1196, 1198, 2716), 2571) (60, 0.8955223880597015, 0.32348111658456485, 0.003484522910738138)
((1196, 1198, 2571), 2716) (60, 0.5357142857142857, 0.08045977011494253, 0.0049148099606815205)
((1196, 1210, 1240), 356) (74, 0.8314606741573034, 0.3957307060755337, 0.002639557695737471)
((356, 1210, 1240), 1196) (74, 0.9736842105263158, 0.20525451559934316, 0.004892885480031738)
((356, 1196, 1240), 1210) (74, 0.9866666666666667, 0.18226600985221675, 0.005333333333333333)
((356, 1196, 1210), 1240) (74, 0.6324786324786325, 0.0755336617405583, 0.005270655270655271)
((296, 593, 1210), 110) (61, 0.7176470588235294, 0.25779967159277506, 0.003291958985429034)
((110, 593, 1210), 296) (61, 0.8714285714285714, 0.37110016420361247, 0.0030363364858138377)
((110, 296, 1210), 593) (61, 0.8243243243243243, 0.3316912972085386, 0.003134313020244579)
((110, 296, 593), 1210) (61, 0.5495495495495496, 0.20361247947454847, 0.002970538105673241)
((50, 110, 356), 47) (68, 0.7640449438202247, 0.2019704433497537, 0.004000235307959291)
((47, 110, 356), 50) (68, 0.6666666666666666, 0.21182266009852216, 0.00338409475465313)
((47, 50, 356), 110) (68, 0.7472527472527473, 0.24630541871921183, 0.003427764895654804)
((47, 50, 110), 356) (68, 0.918918918918919, 0.4055829228243022, 0.002917202917202917)
((1198, 1270, 2115), 1196) (62, 0.9253731343283582, 0.22495894909688013, 0.004650116252906323)
((1196, 1270, 2115), 1198) (62, 0.9393939393939394, 0.2118226600985222, 0.004918292876408059)
((1196, 1198, 2115), 1270) (62, 0.8266666666666667, 0.15927750410509034, 0.00519916142557652)
((1196, 1198, 1270), 2115) (62, 0.6526315789473685, 0.05747126436781609, 0.006728160607704829)
((356, 2028, 2329), 296) (63, 0.9692307692307692, 0.367816091954023, 0.003377110694183865)
((296, 2028, 2329), 356) (63, 0.9, 0.4137931034482759, 0.002857142857142857)
((296, 356, 2329), 2028) (63, 0.7682926829268293, 0.19047619047619047, 0.004292137893445973)
((296, 356, 2028), 2329) (63, 0.6428571428571429, 0.10509031198686371, 0.005061867266591676)
((356, 1198, 2571), 50) (64, 0.6808510638297872, 0.21839080459770116, 0.00345609677070958)
((50, 1198, 2571), 356) (64, 0.8311688311688312, 0.41215106732348117, 0.0026386312100597814)
((50, 356, 2571), 1198) (64, 0.6736842105263158, 0.2085385878489327, 0.0035271424634885644)
((50, 356, 1198), 2571) (64, 0.8533333333333334, 0.3169129720853859, 0.0033203631647211415)
((356, 2028, 2858), 260) (62, 0.7654320987654321, 0.2824302134646962, 0.0032710773451514194)
((260, 2028, 2858), 356) (62, 0.8493150684931506, 0.41543513957307066, 0.002696238312676669)
((260, 356, 2858), 2028) (62, 0.7469879518072289, 0.1921182266009852, 0.004173117049202396)
((260, 356, 2028), 2858) (62, 0.6888888888888889, 0.20361247947454847, 0.003703703703703704)
((1196, 1214, 2028), 260) (64, 0.927536231884058, 0.2791461412151067, 0.003963830050786573)
((260, 1214, 2028), 1196) (64, 0.9696969696969697, 0.22167487684729065, 0.004872849093954621)
((260, 1196, 2028), 1214) (64, 0.6213592233009708, 0.1083743842364532, 0.004779686333084392)
((260, 1196, 1214), 2028) (64, 0.7032967032967034, 0.18883415435139572, 0.003929031861992756)
((356, 648, 1210), 260) (63, 0.9545454545454546, 0.28078817733990147, 0.004079254079254079)
((260, 648, 1210), 356) (63, 0.75, 0.4137931034482759, 0.002380952380952381)
((260, 356, 1210), 648) (63, 0.5384615384615384, 0.13464696223316913, 0.003713527851458886)
((260, 356, 648), 1210) (63, 0.9130434782608695, 0.20032840722495898, 0.004935370152761457)
((296, 1210, 2571), 50) (70, 0.7142857142857143, 0.20853858784893267, 0.0036258158085569255)
((50, 1210, 2571), 296) (70, 0.9090909090909091, 0.3563218390804598, 0.0031675641431738993)
((50, 296, 2571), 1210) (70, 0.693069306930693, 0.18883415435139575, 0.0037463205780037465)
((50, 296, 1210), 2571) (70, 0.8860759493670886, 0.30706075533661736, 0.003447766339949761)
((1198, 1210, 2571), 50) (61, 0.5980392156862745, 0.2233169129720854, 0.0030357320593211905)
((50, 1210, 2571), 1198) (61, 0.7922077922077922, 0.21346469622331693, 0.004147684775957027)
((50, 1198, 2571), 1210) (61, 0.7922077922077922, 0.20361247947454847, 0.004282204282204282)
((50, 1198, 1210), 2571) (61, 0.8840579710144928, 0.3218390804597701, 0.0034399142841030845)
((480, 1196, 1198), 1) (63, 0.7241379310344828, 0.2233169129720854, 0.0036388840755501644)
((1, 1196, 1198), 480) (63, 0.7682926829268293, 0.2512315270935961, 0.003556910569105691)
((1, 480, 1198), 1196) (63, 0.8873239436619719, 0.2233169129720854, 0.004458914289758652)
((1, 480, 1196), 1198) (63, 0.84, 0.21018062397372744, 0.004397905759162304)
((1198, 1270, 2571), 356) (73, 0.8488372093023255, 0.3973727422003284, 0.0026947212993724623)
((356, 1270, 2571), 1198) (73, 0.7849462365591398, 0.19376026272577995, 0.0041096661599954966)
((356, 1198, 2571), 1270) (73, 0.776595744680851, 0.1412151067323481, 0.004884249966546233)
((356, 1198, 1270), 2571) (73, 0.8295454545454546, 0.30213464696223313, 0.0032278033250795896)
((356, 2028, 2571), 296) (91, 0.8198198198198198, 0.32183908045977005, 0.002856515051637003)
((296, 2028, 2571), 356) (91, 0.8666666666666667, 0.367816091954023, 0.0027513227513227515)
((296, 356, 2571), 2028) (91, 0.6893939393939394, 0.14449917898193756, 0.0038513627899102757)
((296, 356, 2028), 2571) (91, 0.9285714285714286, 0.27257799671592775, 0.003613118399110617)
((2028, 2571, 2858), 50) (60, 0.6896551724137931, 0.22495894909688013, 0.003500787677227376)
((50, 2571, 2858), 2028) (60, 0.7228915662650602, 0.1954022988505747, 0.0040385003701958674)
((50, 2028, 2858), 2571) (60, 0.9230769230769231, 0.32348111658456485, 0.0035917390002993114)
((50, 2028, 2571), 2858) (60, 0.75, 0.20689655172413796, 0.004032258064516129)
((2571, 2959, 3578), 593) (63, 0.7078651685393258, 0.32840722495894914, 0.002691502541974623)
((593, 2959, 3578), 2571) (63, 0.9, 0.3185550082101806, 0.003501945525291829)
((593, 2571, 3578), 2959) (63, 0.7974683544303798, 0.2348111658456486, 0.0038712056040309697)
((593, 2571, 2959), 3578) (63, 0.6057692307692307, 0.14778325123152714, 0.003959276018099547)
((356, 2571, 3793), 260) (60, 0.8333333333333334, 0.2857142857142857, 0.0035612535612535613)
((260, 2571, 3793), 356) (60, 0.75, 0.41871921182266014, 0.002380952380952381)
((260, 356, 3793), 2571) (60, 0.9090909090909091, 0.32348111658456485, 0.003537318712415989)
((260, 356, 2571), 3793) (60, 0.5405405405405406, 0.10016420361247948, 0.004467277194549922)
((480, 1270, 1291), 260) (62, 0.9117647058823529, 0.2824302134646962, 0.0038964303670186023)
((260, 1270, 1291), 480) (62, 0.7469879518072289, 0.25287356321839083, 0.0034582775546630968)
((260, 480, 1291), 1270) (62, 0.8051948051948052, 0.15927750410509034, 0.005064118271665441)
((260, 480, 1270), 1291) (62, 0.775, 0.11986863711001643, 0.005740740740740741)
((480, 592, 593), 356) (71, 0.8658536585365854, 0.40065681444991796, 0.002748741773132017)
((356, 592, 593), 480) (71, 0.8352941176470589, 0.2380952380952381, 0.003867102396514161)
((356, 480, 593), 592) (71, 0.5867768595041323, 0.16584564860426929, 0.003411493369210071)
((356, 480, 592), 593) (71, 0.7029702970297029, 0.3152709359605912, 0.0026728908632308096)
((296, 457, 480), 110) (72, 0.7741935483870968, 0.23973727422003285, 0.003551346552234389)
((110, 457, 480), 296) (72, 0.7578947368421053, 0.3530377668308703, 0.002640748211993398)
((110, 296, 480), 457) (72, 0.7058823529411765, 0.18062397372742203, 0.003878474466709761)
((110, 296, 457), 480) (72, 0.7912087912087912, 0.23645320197044337, 0.003663003663003663)
((2571, 2858, 2959), 1089) (61, 0.6161616161616161, 0.10344827586206896, 0.004969045291625937)
((1089, 2858, 2959), 2571) (61, 0.8840579710144928, 0.3218390804597701, 0.0034399142841030845)
((1089, 2571, 2959), 2858) (61, 0.782051282051282, 0.2052545155993432, 0.004204576785221946)
((1089, 2571, 2858), 2959) (61, 0.8026315789473685, 0.23809523809523808, 0.0038962698007153807)
((296, 480, 2571), 110) (60, 0.7142857142857143, 0.2594417077175698, 0.00327653997378768)
((110, 480, 2571), 296) (60, 0.8, 0.3727422003284072, 0.0027874564459930314)
((110, 296, 2571), 480) (60, 0.6521739130434783, 0.2561576354679803, 0.0030193236714975845)
((110, 296, 480), 2571) (60, 0.5882352941176471, 0.32348111658456485, 0.0022888532845044634)
((1210, 2571, 3793), 1196) (73, 0.9358974358974359, 0.2068965517241379, 0.0047030021904393765)
((1196, 2571, 3793), 1210) (73, 0.9358974358974359, 0.1839080459770115, 0.005058905058905059)
((1196, 1210, 3793), 2571) (73, 0.9358974358974359, 0.30213464696223313, 0.0036416242641923577)
((1196, 1210, 2571), 3793) (73, 0.5615384615384615, 0.07881773399014778, 0.004640813731722823)
((608, 1196, 1198), 50) (60, 0.759493670886076, 0.22495894909688013, 0.0038552978217567305)
((50, 1196, 1198), 608) (60, 0.7894736842105263, 0.18226600985221675, 0.0046168051708217915)
((50, 608, 1198), 1196) (60, 0.8571428571428571, 0.22824302134646962, 0.004307250538406317)
((50, 608, 1196), 1198) (60, 0.8333333333333334, 0.21510673234811167, 0.004363001745200698)
((1196, 2329, 2959), 296) (61, 0.9682539682539683, 0.37110016420361247, 0.00337370720645982)
((296, 2329, 2959), 1196) (61, 0.6777777777777778, 0.22660098522167488, 0.0034059184812953655)
((296, 1196, 2959), 2329) (61, 0.6630434782608695, 0.1083743842364532, 0.005220814789455666)
((296, 1196, 2329), 2959) (61, 0.8970588235294118, 0.23809523809523808, 0.0043546544831524845)
((480, 593, 1210), 296) (62, 0.8051948051948052, 0.3694581280788177, 0.0028055568125254535)
((296, 593, 1210), 480) (62, 0.7294117647058823, 0.25287356321839083, 0.0033769063180827887)
((296, 480, 1210), 593) (62, 0.8157894736842105, 0.3300492610837439, 0.003101861116670002)
((296, 480, 593), 1210) (62, 0.5794392523364486, 0.20197044334975373, 0.003132104066683506)
((1196, 1210, 1265), 1) (64, 0.7710843373493976, 0.22167487684729065, 0.0038747956650723495)
((1, 1210, 1265), 1196) (64, 0.9696969696969697, 0.22167487684729065, 0.004872849093954621)
((1, 1196, 1265), 1210) (64, 0.9411764705882353, 0.19868637110016424, 0.005087440381558029)
((1, 1196, 1210), 1265) (64, 0.7111111111111111, 0.11330049261083745, 0.005346700083542189)
((260, 780, 1210), 1) (68, 0.7472527472527473, 0.21510673234811165, 0.0037550389309183277)
((1, 780, 1210), 260) (68, 0.9577464788732394, 0.27257799671592775, 0.004092933670398459)
((1, 260, 1210), 780) (68, 0.7157894736842105, 0.15763546798029557, 0.0043645699614890884)
((1, 260, 780), 1210) (68, 0.85, 0.19211822660098524, 0.0045945945945945945)
((1196, 1198, 1240), 480) (61, 0.7721518987341772, 0.2545155993431856, 0.003574777308954524)
((480, 1198, 1240), 1196) (61, 0.9242424242424242, 0.22660098522167488, 0.004644434292675499)
((480, 1196, 1240), 1198) (61, 0.8133333333333334, 0.21346469622331693, 0.004258289703315881)
((480, 1196, 1198), 1240) (61, 0.7011494252873564, 0.09688013136288999, 0.005842911877394636)
((1210, 1270, 2028), 260) (65, 0.9701492537313433, 0.277504105090312, 0.0041459369817578775)
((260, 1270, 2028), 1210) (65, 0.9285714285714286, 0.1970443349753695, 0.005019305019305019)
((260, 1210, 2028), 1270) (65, 0.6701030927835051, 0.1543513957307061, 0.004214484860273617)
((260, 1210, 1270), 2028) (65, 0.625, 0.18719211822660098, 0.0034916201117318434)
((296, 356, 527), 50) (80, 0.7079646017699115, 0.1921182266009852, 0.0035937289429944746)
((50, 356, 527), 296) (80, 0.898876404494382, 0.3399014778325123, 0.003131973534823631)
((50, 296, 527), 356) (80, 0.8421052631578947, 0.3858784893267652, 0.0026733500417710945)
((50, 296, 356), 527) (80, 0.6504065040650406, 0.20525451559934316, 0.003172714653975808)
((356, 593, 3578), 296) (65, 0.8666666666666667, 0.3645320197044335, 0.0030197444831591173)
((296, 593, 3578), 356) (65, 0.9154929577464789, 0.4105090311986864, 0.002906326849988822)
((296, 356, 3578), 593) (65, 0.7738095238095238, 0.32512315270935965, 0.002942241535397429)
((296, 356, 593), 3578) (65, 0.4482758620689655, 0.14449917898193765, 0.002929907595221997)
((356, 1210, 1270), 50) (61, 0.6630434782608695, 0.2233169129720854, 0.0033657029353343633)
((50, 1210, 1270), 356) (61, 0.9242424242424242, 0.4170771756978654, 0.002934102934102934)
((50, 356, 1270), 1210) (61, 0.8472222222222222, 0.20361247947454847, 0.00457957957957958)
((50, 356, 1210), 1270) (61, 0.7530864197530864, 0.16091954022988508, 0.004736392577063437)
((260, 2571, 3578), 50) (60, 0.631578947368421, 0.22495894909688013, 0.0032059845044082286)
((50, 2571, 3578), 260) (60, 0.8450704225352113, 0.2857142857142857, 0.0036114120621162874)
((50, 260, 3578), 2571) (60, 0.9523809523809523, 0.32348111658456485, 0.0037057624606262737)
((50, 260, 2571), 3578) (60, 0.6976744186046512, 0.15270935960591137, 0.004559963520291838)
((296, 593, 1196), 47) (68, 0.68, 0.2019704433497537, 0.0035602094240837698)
((47, 593, 1196), 296) (68, 0.918918918918919, 0.35960591133004927, 0.0032018080798568603)
((47, 296, 1196), 593) (68, 0.8395061728395061, 0.3201970443349754, 0.0031920386799981224)
((47, 296, 593), 1196) (68, 0.5528455284552846, 0.21510673234811165, 0.002778118233443641)
((1210, 1270, 2571), 593) (62, 0.6888888888888889, 0.3300492610837439, 0.002619349387410224)
((593, 1270, 2571), 1210) (62, 0.8611111111111112, 0.20197044334975373, 0.0046546546546546545)
((593, 1210, 2571), 1270) (62, 0.6966292134831461, 0.15927750410509034, 0.004381315808070101)
((593, 1210, 1270), 2571) (62, 0.8378378378378378, 0.32019704433497537, 0.00326006940792933)
((593, 2571, 2959), 50) (71, 0.6826923076923077, 0.20689655172413793, 0.003465443186255369)
((50, 2571, 2959), 593) (71, 0.8068181818181818, 0.3152709359605912, 0.003067749740753543)
((50, 593, 2959), 2571) (71, 0.8255813953488372, 0.3054187192118226, 0.0032123789702289385)
((50, 593, 2571), 2959) (71, 0.8255813953488372, 0.22167487684729062, 0.004007676676450666)
((260, 356, 2571), 1) (68, 0.6126126126126126, 0.21510673234811165, 0.0030784553397618726)
((1, 356, 2571), 260) (68, 0.7472527472527473, 0.27257799671592775, 0.0031933878087724243)
((1, 260, 2571), 356) (68, 0.8607594936708861, 0.4055829228243022, 0.0027325698211774162)
((1, 260, 356), 2571) (68, 0.7727272727272727, 0.31034482758620685, 0.0030067209055535905)
((1210, 1291, 2571), 260) (86, 0.9555555555555556, 0.2430213464696223, 0.004083570750237417)
((260, 1291, 2571), 1210) (86, 0.945054945054945, 0.16256157635467983, 0.0051084051084051086)
((260, 1210, 2571), 1291) (86, 0.6825396825396826, 0.08045977011494254, 0.005055849500293945)
((260, 1210, 1291), 2571) (86, 0.8431372549019608, 0.28078817733990147, 0.0032806897077897307)
((1210, 2571, 3578), 356) (73, 0.8295454545454546, 0.3973727422003284, 0.0026334776334776336)
((356, 2571, 3578), 1210) (73, 0.7373737373737373, 0.1839080459770115, 0.003985803985803986)
((356, 1210, 3578), 2571) (73, 0.9605263157894737, 0.30213464696223313, 0.0037374564816711037)
((356, 1210, 2571), 3578) (73, 0.6759259259259259, 0.13136288998357964, 0.004417816509319777)
((1210, 1291, 2571), 296) (68, 0.7555555555555555, 0.35960591133004927, 0.002632597754548974)
((296, 1291, 2571), 1210) (68, 0.8831168831168831, 0.19211822660098524, 0.004773604773604774)
((296, 1210, 2571), 1291) (68, 0.6938775510204082, 0.11001642036124795, 0.0051398337112622825)
((296, 1210, 1291), 2571) (68, 0.8607594936708861, 0.31034482758620685, 0.003349258730236911)
((1210, 2028, 2571), 260) (89, 0.89, 0.23809523809523808, 0.0038034188034188035)
((260, 2028, 2571), 1210) (89, 0.8725490196078431, 0.1576354679802956, 0.004716481187069422)
((260, 1210, 2571), 2028) (89, 0.7063492063492064, 0.14778325123152708, 0.0039460849516715435)
((260, 1210, 2028), 2571) (89, 0.9175257731958762, 0.27586206896551724, 0.0035701391953146936)
((1089, 1196, 2571), 356) (64, 0.8311688311688312, 0.41215106732348117, 0.0026386312100597814)
((356, 1196, 2571), 1089) (64, 0.5765765765765766, 0.09852216748768473, 0.004649811101424005)
((356, 1089, 2571), 1196) (64, 0.8, 0.22167487684729065, 0.004020100502512563)
((356, 1089, 1196), 2571) (64, 0.9014084507042254, 0.3169129720853859, 0.0035074258782265577)
((260, 1210, 1291), 1) (71, 0.696078431372549, 0.21018062397372742, 0.003497881564686176)
((1, 1210, 1291), 260) (71, 0.9726027397260274, 0.2676518883415435, 0.0041564219646411426)
((1, 260, 1291), 1210) (71, 0.9726027397260274, 0.187192118226601, 0.005257312106627175)
((1, 260, 1210), 1291) (71, 0.7473684210526316, 0.10509031198686372, 0.005536062378167642)
((356, 527, 593), 50) (71, 0.6396396396396397, 0.20689655172413793, 0.0032469017240590843)
((50, 527, 593), 356) (71, 0.8658536585365854, 0.40065681444991796, 0.002748741773132017)

In [ ]:
# Convert scores dict to DataFrame
scores_df = pd.DataFrame([
    {'antecedent': k[0], 'consequent': k[1], 'support': v[0], 'confidence': v[1], 'interest': v[2], 'lift': v[3]}
    for k, v in scores.items()
])

# Calculate mean and std for each metric
metrics = ['support', 'confidence', 'interest', 'lift']
means = scores_df[metrics].mean()
stds = scores_df[metrics].std()
print("Means:\n", means)
print("Standard Deviations:\n", stds)

# Define significance as > mean + 1 std
sig = {m: means[m] + stds[m] for m in metrics}

# Filter for significant rules per metric
# for m in metrics:
#     print(f"\nSignificant {m} (> mean+std):")
#     display(scores_df[scores_df[m] > sig[m]].sort_values(m, ascending=False))

# Filter for rules significant in all metrics
all_sig = scores_df[
    ((scores_df['confidence'] > sig['confidence']) &
    (scores_df['interest'] > sig['interest'])) #|
    # ((scores_df['confidence'] > sig['confidence']) &
    # (scores_df['lift'] > sig['lift'])) |
    # ((scores_df['interest'] > sig['interest']) &
    # (scores_df['lift'] > sig['lift']))
]
print("\nRules significant in all metrics:")
# display(all_sig)
print(all_sig.loc[~all_sig['consequent'].isin([296,356])].to_markdown(index=False))
# print(all_sig.to_markdown(index=False))

Means:
 support       65.646369
confidence     0.828606
interest       0.244807
lift           0.004032
dtype: float64
Standard Deviations:
 support       6.429397
confidence    0.119338
interest      0.085707
lift          0.000904
dtype: float64

Rules significant in all metrics:
| antecedent        |   consequent |   support |   confidence |   interest |       lift |
|:------------------|-------------:|----------:|-------------:|-----------:|-----------:|
| (296, 1258, 2571) |          593 |        60 |     0.952381 |   0.333333 | 0.00362122 |

In Ab4I I stored all of the supports for frequent items, in step 2 I created a dict of tuples for each 'j' movieId as an implied consequence of the others and calculated the confidence, interest, and lift of each combination. I asked copilot to convert this messy data structure to a dataframe and to look for significant (> mean+1stdev) scores.\
lift doesn't seem too useful to us\
When we search 4-8 length baskets we find that all but 1 of the significant scoring baskets attempt to identify 296 or 356\
Some choice rows that are > mean + 1stdev in confidence and interest
| antecedent                         |   consequent |   support |   confidence |   interest |       lift |
|:-----------------------------------|-------------:|----------:|-------------:|-----------:|-----------:|
| (296, 1258, 2571)                  |          593 |        60 |     0.952381 |   0.333333 | 0.00362122 |
| (593, 1089, 2571)                  |          296 |        75 |     0.974026 |   0.348112 | 0.00339382 |
| (1196, 1213, 2959)                 |          296 |        60 |     0.983607 |   0.372742 | 0.0034272  |
| (110, 480, 500)                    |          356 |        61 |     1        |   0.417077 | 0.0031746  |
| (50, 480, 593)                     |          356 |        75 |     0.949367 |   0.394089 | 0.00301386 |
| (593, 2028, 7153)                  |          356 |        60 |     0.983607 |   0.418719 | 0.00312256 |
| (110, 260, 296, 2959)              |          356 |        60 |     0.967742 |   0.418719 | 0.0030722  |

(2571, 4226)->318\
(50, 593, 2959)->318\
(593, 2571, 2959)->318\
and additional relationships with 50 and 296\
\
593, 2571, 2959 appear heavily in both results\
We will look deeper into these patterns

In [ ]:
D = dict()
D[(296, 1258, 2571)] = 593
D[(593, 1089, 2571)] = 296
D[(1196, 1213, 2959)] = 296
D[(110, 480, 500)] = 356
D[(50, 480, 593)] = 356
D[(593, 2028, 7153)] = 356
D[(110, 260, 296, 2959)] = 356

for k,v in D.items():
    print(f'{k}->{v}: {Ab4I[len(k)][tuple(sorted(list(k)+[v]))]}')
print(Ab4I[0][296], Ab4I[0][356], Ab4I[0][318]) # ~300 nothing exceptional

(296, 1258, 2571)->593: 60
(593, 1089, 2571)->296: 75
(1196, 1213, 2959)->296: 60
(110, 480, 500)->356: 61
(50, 480, 593)->356: 75
(593, 2028, 7153)->356: 60
(110, 260, 296, 2959)->356: 60
287 315 313

In [ ]:
allTitles = pd.read_csv("ml-latest-small/movies.csv")
title_map = dict(zip(allTitles['movieId'], allTitles['title']))
for k,v in D.items():
    s = ', '.join([title_map.get(mid, str(mid)) for mid in k])
    print(f'{s}  ->  {title_map[v]}')

Pulp Fiction (1994), Shining, The (1980), Matrix, The (1999)  ->  Silence of the Lambs, The (1991)
Silence of the Lambs, The (1991), Reservoir Dogs (1992), Matrix, The (1999)  ->  Pulp Fiction (1994)
Star Wars: Episode V - The Empire Strikes Back (1980), Goodfellas (1990), Fight Club (1999)  ->  Pulp Fiction (1994)
Braveheart (1995), Jurassic Park (1993), Mrs. Doubtfire (1993)  ->  Forrest Gump (1994)
Usual Suspects, The (1995), Jurassic Park (1993), Silence of the Lambs, The (1991)  ->  Forrest Gump (1994)
Silence of the Lambs, The (1991), Saving Private Ryan (1998), Lord of the Rings: The Return of the King, The (2003)  ->  Forrest Gump (1994)
Braveheart (1995), Star Wars: Episode IV - A New Hope (1977), Pulp Fiction (1994), Fight Club (1999)  ->  Forrest Gump (1994)

Yes, these are some good groups of movies
Everyone that liked Braveheart, Jurassic Park, and Mrs. Doubtfire liked Forrest Gump as well

### (10pts) Step 3: Implement Random Sampling

We discussed in class a method to randomly sample baskets to avoid the overhead of reading the entire set of baskets (which in practice, could amount to billions of baskets). For this part, you should implement such a random sampling approach that takes a special parameter **alpha** that controls the size of the sample: e.g., alpha = 0.10 means to sample 10% of the baskets (our users, in this case).

Vary **alpha** and report the number of frequent itemsets you find and how this compares to the number of frequent itemsets in the entire dataset. What do you discover?

In [ ]:
alphas = [0.075, 0.1, 0.15, 0.2]
minsups = [10, 12, 14, 16]
omegas = []
R = dict()

for a, minsup in zip(alphas, minsups):
    print(f'\nAlpha: {a} --minsup {minsup}-------')
    sampled_users = likes_df.sample(frac=a, random_state=42)
    Rpriori = Apriori(sampled_users, minsup=minsup)
    R[a] = Rpriori
    s = 0
    for x in range(len(Rpriori)):
        s += len(Rpriori[x])
    omegas.append(s)
for a,o in zip(alphas, omegas):
    print(f'Alpha: {a}: {o}')

Alpha: 0.075 --minsup 10-------
Found 93 frequent 1-itemsets
Found 334 frequent 2-itemsets
Found 331 frequent 3-itemsets
Found 188 frequent 4-itemsets
Found 70 frequent 5-itemsets
Found 15 frequent 6-itemsets
Found 1 frequent 7-itemsets
Found 0 frequent 8-itemsets

Alpha: 0.1 --minsup 12-------
Found 99 frequent 1-itemsets
Found 438 frequent 2-itemsets
Found 463 frequent 3-itemsets
Found 238 frequent 4-itemsets
Found 62 frequent 5-itemsets
Found 7 frequent 6-itemsets
Found 0 frequent 7-itemsets

Alpha: 0.15 --minsup 14-------
Found 169 frequent 1-itemsets
Found 1261 frequent 2-itemsets
Found 1894 frequent 3-itemsets
Found 1682 frequent 4-itemsets
Found 864 frequent 5-itemsets
Found 310 frequent 6-itemsets
Found 72 frequent 7-itemsets
Found 8 frequent 8-itemsets
Found 0 frequent 9-itemsets

Alpha: 0.2 --minsup 16-------
Found 199 frequent 1-itemsets
Found 2022 frequent 2-itemsets
Found 3331 frequent 3-itemsets
Found 3167 frequent 4-itemsets
Found 1637 frequent 5-itemsets
Found 517 frequent 6-itemsets
Found 101 frequent 7-itemsets
Found 9 frequent 8-itemsets
Found 0 frequent 9-itemsets
Alpha: 0.075: 1032
Alpha: 0.1: 1307
Alpha: 0.15: 6260
Alpha: 0.2: 10983

Its a percarious balance between minsup and sample size, and I found it best not to directly relate it to the full-scale minsup. Instead I attempted to shape the results similarly to the baskets we got in the full set, it was a good balance between finding next to nothing and exploding magnitudes of candidates.

### (10pts) Step 4: Check for False Positives

Next you should verify that the candidate pairs you discover by random sampling are truly frequent by comparing to the itemsets you discover over the entire dataset.

For this part, consider another parameter **minsup_sample** that relaxes the minimum support threshold. For example if we want minsup = 1/100 for whole dataset, then try minsup_sample = 1/125 for the sample. This will help catch truly frequent itemsets.

Vary **minsup_sample** and report the number of frequent itemsets you find and the number of false positives you find. What do you discover?

In [ ]:
for a in alphas:
    print(f'\nAlpha: {a} ------------------')
    FP = 0
    L = 0
    for kbasket in R[a]:
        L+=len(kbasket.items())
        for k,v in kbasket.items():
            l = 1 if type(k) is int else len(k)
            if k not in Ab4I[l-1].keys():
                FP += 1
    print(f'False Positives: {FP}: {round(FP/L * 100, 3)}% of {L} total')

minsups2 = [x + 2 for x in minsups]
print('\n\nincrease minsups by 2')
for a, minsup in zip(alphas, minsups2):
    # print(f'\nAlpha: {a} --minsup {minsup}-------')
    sampled_users = likes_df.sample(frac=a, random_state=42)
    Rpriori = Apriori(sampled_users, minsup=minsup, muted=True)
    R[a] = Rpriori
    s = 0
    for x in range(len(Rpriori)):
        s += len(Rpriori[x])
    omegas.append(s)
for a in alphas:
    print(f'\nAlpha: {a} ------------------')
    FP = 0
    L = 0
    for kbasket in R[a]:
        L+=len(kbasket.items())
        for k,v in kbasket.items():
            l = 1 if type(k) is int else len(k)
            if k not in Ab4I[l-1].keys():
                FP += 1
    print(f'False Positives: {FP}: {round(FP/L * 100, 3)}% of {L} total')

Alpha: 0.075 ------------------
False Positives: 405: 39.244% of 1032 total

Alpha: 0.1 ------------------
False Positives: 605: 46.289% of 1307 total

Alpha: 0.15 ------------------
False Positives: 3714: 59.329% of 6260 total

Alpha: 0.2 ------------------
False Positives: 6681: 60.83% of 10983 total


increase minsups by 2

Alpha: 0.075 ------------------
False Positives: 58: 28.571% of 203 total

Alpha: 0.1 ------------------
False Positives: 138: 34.673% of 398 total

Alpha: 0.15 ------------------
False Positives: 711: 39.282% of 1810 total

Alpha: 0.2 ------------------
False Positives: 1682: 41.521% of 4051 total

I selected specified minsups per sample size to keep freq itemlists in a similar basket-size spread to our full length check. With lower minsups more and longer baskets are found, with higher less and shorter. The larger the minsup the less false-positives we find. When we increase our minsups by 2, we typically find up to only 7-length baskets, but significantly less False Positives.

## (5 points) Part 3: Spark-based Association Rules

So far, we have been working with a fairly small dataset. For this last question, you should use the much larger **Movies 10M** dataset: https://files.grouplens.org/datasets/movielens/ml-10m.zip

First, we need to load this larger dataset:

In [ ]:
import urllib3
import zipfile

http = urllib3.PoolManager()
req = http.request("GET", "https://files.grouplens.org/datasets/movielens/ml-10m.zip", preload_content=False)

with open("movie.zip", 'wb') as out:
  while True:
    data = req.read(4096)
    if not data:
      break
    out.write(data)
req.release_conn()

zFile = zipfile.ZipFile("movie.zip", "r")
for fileM in zFile.namelist():
  zFile.extract(fileM)

Now, see if you can write a Spark-based implementaiton of Apriori. You'll see that the Spark library MLib does contain a "Frequent Pattern Mining" implementation. You may not use this! Good luck!

In [10]:
import itertools
from pyspark.sql import SparkSession
from pyspark.sql import functions as F

# --- Spark session ---
spark = SparkSession.builder \
    .master("local[*]") \
    .appName("AprioriCustom") \
    .getOrCreate()


# --- Load MovieLens data (10M) ---
movies = spark.read.text("ml-10M100K/movies.dat") \
    .selectExpr("split(value, '::') as cols") \
    .selectExpr("cols[0] as movieId", "cols[1] as title", "cols[2] as genres")

ratings = spark.read.text("ml-10M100K/ratings.dat") \
    .selectExpr("split(value, '::') as cols") \
    .selectExpr("cols[0] as userId", "cols[1] as movieId", "cols[2] as rating", "cols[3] as timestamp")

print(f'Ratings: {ratings.count()}')
print(f'Movies: {movies.count()}')
# Filter ratings >= 3
ratings_filtered = ratings.filter(ratings.rating.cast("float") >= 3)

# Transactions = user → set of movieIds
transactions_df = ratings_filtered.groupBy("userId") \
    .agg(F.collect_set("movieId").alias("likes"))

transactions = transactions_df.rdd.map(lambda row: row.likes).cache()
total_users = transactions.count()
minsup_count = 14000
print(f"Using minsup = {minsup_count} ({round(minsup_count/total_users,3)*100}% of {total_users} users)")


# --- Apriori functions ---

def frequent_singletons(transactions, minsup):
    return (transactions
            .flatMap(lambda t: [(i, 1) for i in t])
            .reduceByKey(lambda x, y: x + y)
            .filter(lambda kv: kv[1] >= minsup)
            .collectAsMap())


def generate_candidates(F_prev, k):
    # Build the universe of items from F_prev keys (strings for k=1, tuples for k>=2)
    items = set(itertools.chain.from_iterable(
        [key if isinstance(key, tuple) else (key,) for key in F_prev.keys()]
    ))

    def subset_in_prev(sub):
        """Membership test that respects how F_prev stores keys."""
        if len(sub) == 1:
            return sub[0] in F_prev           # k-1 == 1 → F_prev has scalar keys
        else:
            return tuple(sorted(sub)) in F_prev  # k-1 >= 2 → F_prev has tuple keys

    candidates = set()
    for base in F_prev.keys():
        base = base if isinstance(base, tuple) else (base,)
        for item in items:
            if item not in base:
                new_cand = tuple(sorted(base + (item,)))
                # Apriori prune: all (k-1)-subsets must be frequent
                if all(subset_in_prev(s) for s in itertools.combinations(new_cand, k-1)):
                    candidates.add(new_cand)
    return candidates



def count_support(transactions, candidates, minsup):
    cand_broadcast = transactions.context.broadcast(list(candidates))
    Fk = (transactions
          .flatMap(lambda t: [cand for cand in cand_broadcast.value if set(cand).issubset(t)])
          .map(lambda cand: (cand, 1))
          .reduceByKey(lambda x, y: x + y)
          .filter(lambda kv: kv[1] >= minsup)
          .collectAsMap())
    cand_broadcast.unpersist()
    return Fk


def apriori(transactions, minsup):
    F = []
    print("Generating frequent 1-itemsets...")
    F1 = frequent_singletons(transactions, minsup)
    print(f"Found {len(F1)} frequent 1-itemsets")
    F.append(F1)

    k = 2
    while F[k-2]:
        print(f"\nGenerating candidates for k={k}...")
        candidates = generate_candidates(F[k-2], k)
        print(f"  Candidate count = {len(candidates)}")

        Fk = count_support(transactions, candidates, minsup)
        print(f"  Found {len(Fk)} frequent {k}-itemsets")

        F.append(Fk)
        k += 1

    print("\nApriori complete.")
    return F


# --- Run Apriori ---
Ab4I_spark = apriori(transactions, minsup=minsup_count)

# --- Map movieIds → titles ---
movies_dict = {row.movieId: row.title for row in movies.collect()}

def itemset_to_titles(itemset):
    return [movies_dict[i] for i in (itemset if isinstance(itemset, tuple) else (itemset,))]

# Print results (cautious: can be large)
for k, Fk in enumerate(Ab4I_spark, start=1):
    print(f"\n{k}-itemsets:")
    for itemset, support in list(Fk.items())[:20]:  # show top 20 only
        titles = itemset_to_titles(itemset)
        print(f"  {titles} (support={support})")

Ratings: 10000054
Movies: 10681
Using minsup = 14000 (20.0% of 69863 users)
Generating frequent 1-itemsets...
Found 66 frequent 1-itemsets

Generating candidates for k=2...
  Candidate count = 2145
  Found 118 frequent 2-itemsets

Generating candidates for k=3...
  Candidate count = 298
  Found 35 frequent 3-itemsets

Generating candidates for k=4...
  Candidate count = 16
  Found 0 frequent 4-itemsets

Apriori complete.

1-itemsets:
  ['Braveheart (1995)'] (support=27137)
  ['Mask, The (1994)'] (support=15011)
  ['Terminator 2: Judgment Day (1991)'] (support=27050)
  ['Back to the Future (1985)'] (support=19885)
  ['Star Wars: Episode V - The Empire Strikes Back (1980)'] (support=21982)
  ['Four Weddings and a Funeral (1994)'] (support=14967)
  ['Dances with Wolves (1990)'] (support=23445)
  ['Pulp Fiction (1994)'] (support=32338)
  ['12 Monkeys (Twelve Monkeys) (1995)'] (support=22823)
  ['Batman (1989)'] (support=23934)
  ['Rock, The (1996)'] (support=16155)
  ['Fargo (1996)'] (support=22340)
  ['Shawshank Redemption, The (1994)'] (support=30563)
  ['Forrest Gump (1994)'] (support=31860)
  ['Jurassic Park (1993)'] (support=29114)
  ['Babe (1995)'] (support=16413)
  ['Gladiator (2000)'] (support=14102)
  ['Lord of the Rings: The Fellowship of the Ring, The (2001)'] (support=14754)
  ['Die Hard (1988)'] (support=14811)
  ['Indiana Jones and the Last Crusade (1989)'] (support=15395)

2-itemsets:
  ['Terminator 2: Judgment Day (1991)', 'Batman (1989)'] (support=15624)
  ['Braveheart (1995)', 'Jurassic Park (1993)'] (support=17579)
  ['Shawshank Redemption, The (1994)', 'Jurassic Park (1993)'] (support=17268)
  ['Shawshank Redemption, The (1994)', 'Forrest Gump (1994)'] (support=19808)
  ['Pulp Fiction (1994)', 'Dances with Wolves (1990)'] (support=16241)
  ['Jurassic Park (1993)', 'Batman (1989)'] (support=17000)
  ['Shawshank Redemption, The (1994)', 'Terminator 2: Judgment Day (1991)'] (support=16270)
  ['Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)', 'Star Wars: Episode IV - A New Hope (a.k.a. Star Wars) (1977)'] (support=16045)
  ['Forrest Gump (1994)', 'Terminator 2: Judgment Day (1991)'] (support=18752)
  ['Jurassic Park (1993)', 'Terminator 2: Judgment Day (1991)'] (support=20149)
  ["Schindler's List (1993)", 'Silence of the Lambs, The (1991)'] (support=17526)
  ['Braveheart (1995)', 'Pulp Fiction (1994)'] (support=18138)
  ['Braveheart (1995)', 'Shawshank Redemption, The (1994)'] (support=17740)
  ['Star Wars: Episode V - The Empire Strikes Back (1980)', 'Back to the Future (1985)'] (support=14080)
  ['Braveheart (1995)', 'Forrest Gump (1994)'] (support=18737)
  ['Braveheart (1995)', 'Batman (1989)'] (support=14766)
  ['Jurassic Park (1993)', 'Dances with Wolves (1990)'] (support=15863)
  ['Shawshank Redemption, The (1994)', 'Batman (1989)'] (support=15320)
  ['Forrest Gump (1994)', 'Batman (1989)'] (support=16640)
  ['Braveheart (1995)', 'Terminator 2: Judgment Day (1991)'] (support=16831)

3-itemsets:
  ['Forrest Gump (1994)', 'Terminator 2: Judgment Day (1991)', 'Silence of the Lambs, The (1991)'] (support=14193)
  ['Pulp Fiction (1994)', 'Shawshank Redemption, The (1994)', 'Silence of the Lambs, The (1991)'] (support=16889)
  ['Pulp Fiction (1994)', 'Jurassic Park (1993)', 'Silence of the Lambs, The (1991)'] (support=14620)
  ['Jurassic Park (1993)', 'Terminator 2: Judgment Day (1991)', 'Silence of the Lambs, The (1991)'] (support=14428)
  ['Pulp Fiction (1994)', 'Terminator 2: Judgment Day (1991)', 'Silence of the Lambs, The (1991)'] (support=14486)
  ['Forrest Gump (1994)', 'Jurassic Park (1993)', 'Silence of the Lambs, The (1991)'] (support=15594)
  ['Pulp Fiction (1994)', 'Forrest Gump (1994)', 'Silence of the Lambs, The (1991)'] (support=16109)
  ['Shawshank Redemption, The (1994)', 'Forrest Gump (1994)', 'Silence of the Lambs, The (1991)'] (support=15219)
  ['Braveheart (1995)', 'Pulp Fiction (1994)', 'Silence of the Lambs, The (1991)'] (support=14150)
  ['Apollo 13 (1995)', 'Fugitive, The (1993)', 'Silence of the Lambs, The (1991)'] (support=14021)
  ['Pulp Fiction (1994)', 'Fugitive, The (1993)', 'Silence of the Lambs, The (1991)'] (support=15720)
  ['Fugitive, The (1993)', 'Jurassic Park (1993)', 'Silence of the Lambs, The (1991)'] (support=14712)
  ['Shawshank Redemption, The (1994)', 'Fugitive, The (1993)', 'Silence of the Lambs, The (1991)'] (support=14916)
  ['Fugitive, The (1993)', 'Terminator 2: Judgment Day (1991)', 'Silence of the Lambs, The (1991)'] (support=14103)
  ['Forrest Gump (1994)', 'Fugitive, The (1993)', 'Silence of the Lambs, The (1991)'] (support=15233)
  ['Forrest Gump (1994)', 'Jurassic Park (1993)', 'Terminator 2: Judgment Day (1991)'] (support=15571)
  ['Pulp Fiction (1994)', 'Forrest Gump (1994)', 'Terminator 2: Judgment Day (1991)'] (support=14085)
  ['Pulp Fiction (1994)', 'Shawshank Redemption, The (1994)', 'Forrest Gump (1994)'] (support=15147)
  ['Pulp Fiction (1994)', 'Jurassic Park (1993)', 'Terminator 2: Judgment Day (1991)'] (support=14086)
  ['Pulp Fiction (1994)', 'Forrest Gump (1994)', 'Jurassic Park (1993)'] (support=15190)

4-itemsets: